In [1]:
# --- BIBLIOTHÈQUES STANDARDS (Python) ---
import re               # Pour les expressions régulières (supprimer les URLs)
import string           # Pour accéder à la liste complète de ponctuation

# --- NLP : PRÉTRAITEMENT & RACINISATION (NLTK) ---
import nltk             # La base pour la tokenization et les stopwords
from nltk.tokenize import word_tokenize        # Pour découper le texte en mots
from nltk.corpus import stopwords              # Pour filtrer les mots vides (the, is, etc.)
from nltk.stem.porter import PorterStemmer    # Pour le stemming (racinisation)

# --- NLP : ANALYSE AVANCÉE (spaCy & TextBlob) ---
import spacy            # Pour la lemmatisation et le tagging haute précision
from textblob import TextBlob # Pour l'analyse de sentiment et les corrections rapides

# --- OUTILS SPÉCIALISÉS ---
import inflect          # Pour convertir les chiffres (3) en mots (three)
import emoji            # Pour détecter et supprimer les emojis 

# Pour NLTK
nltk.download('punkt')      # Modèle de tokenisation
nltk.download('stopwords')  # Liste des mots vides

# Pour spaCy : téléchargement du modèle anglais (à exécuter une seule fois)
!python -m spacy download en_core_web_sm

[nltk_data] Downloading package punkt to /Users/Licas/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/Licas/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

zsh:1: command not found: python

In [2]:
import pandas as pd

df = pd.read_csv('SMS_test.csv', encoding='latin-1')

In [3]:


df.isnull().sum()

S. No.          0
Message_body    0
Label           0
dtype: int64

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S. No.        125 non-null    int64
 1   Message_body  125 non-null    str
 2   Label         125 non-null    str
dtypes: int64(1), str(2)
memory usage: 18.4 KB

           S. No.
count  125.000000
mean    63.000000
std     36.228442
min      1.000000
25%     32.000000
50%     63.000000
75%     94.000000
max    125.000000

In [5]:
df.head(10)

   S. No.                                       Message_body Label
0       1  UpgrdCentre Orange customer, you may now claim...  Spam
1       2  Loan for any purpose £500 - £75,000. Homeowner...  Spam
2       3  Congrats! Nokia 3650 video camera phone is you...  Spam
3       4  URGENT! Your Mobile number has been awarded wi...  Spam
4       5  Someone has contacted our dating service and e...  Spam
5       6  Send a logo 2 ur lover - 2 names joined by a h...  Spam
6       7  FREE entry into our £250 weekly competition ju...  Spam
7       8  100 dating service cal;l 09064012103 box334sk38ch  Spam
8       9  FREE RINGTONE text FIRST to 87131 for a poly o...  Spam
9      10  4mths half price Orange line rental & latest c...  Spam

In [6]:
messages = df["Message_body"]

messages.head()

0    UpgrdCentre Orange customer, you may now claim...
1    Loan for any purpose £500 - £75,000. Homeowner...
2    Congrats! Nokia 3650 video camera phone is you...
3    URGENT! Your Mobile number has been awarded wi...
4    Someone has contacted our dating service and e...
Name: Message_body, dtype: str

# Text Normalization (Lowercasing, Handling contractions, Spell schecking)

In [7]:
# Lowercasing

# on définit notre fonction lowercase
def text_lower(text):
    return text.str.lower()


# on utilise notre fct
text = text_lower(messages)

In [8]:
print(text)

# on check si TOUTE la colonne est déjà en minuscules
est_propre = text.equals(text.str.lower())
print(f"\nLa colonne est-elle totalement en minuscules ? {est_propre}")

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th ur style 5th...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when u are in love: "1.u like listeni...
124    great. have a safe trip. dont panic surrender ...
Name: Message_body, Length: 125, dtype: str

La colonne est-elle totalement en minuscules ? True

In [9]:
# dealing with contractions

import contractions

def fix_contractions(text):
    if not isinstance(text, str):
        return text
    
    expanded_text = contractions.fix(text)
    return expanded_text

text = fix_contractions(text)

In [10]:
print(text)

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th ur style 5th...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when u are in love: "1.u like listeni...
124    great. have a safe trip. dont panic surrender ...
Name: Message_body, Length: 125, dtype: str

In [11]:
def fix_contractions(text_list):
    return [contractions.fix(message) for message in text_list]


text = fix_contractions(text)
print(text[0]) # Devrait afficher "...you may now claim..."

upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available

In [12]:
# spell checking 
!pip install autocorrect
from autocorrect import Speller


def correct(text_list, lang="en"):
    "Correct spellin using autocorrect for english."
    spell = Speller(lang=lang)
    return [spell(message) for message in text_list]

text = correct(text)

Requirement already satisfied: autocorrect in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.6.1)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [13]:
print(text)

["upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available", "loan for any purpose £500 - £75,000. homeowners + tenants welcome. have you been previously refused? we can still help. call free 0800 1956669 or text back 'help'", 'contrast! nokia 3650 video camera phone is your call 09066382422 calls cost 150ppm ave call 3mins vary from mobiles 16+ close 300603 post bcm4284 lon wc1n3xx', 'urgent! your mobile number has been awarded with a £2000 prize guaranteed. call 09058094455 from land line. claim 3030. valid 12hrs only', 'someone has contacted our dating service and entered your phone because they fancy you! to find out who it is call from a landing 09111032124 . box12n146tf150p', 'send a logo 2 you are lover - 2 names joined by a heart. txt love name1 name2 mono eg love adam eve 07123456789 to 87077 yahoo! box36504w45wq xeno 4 no ads 150p', 'free entry into our £250 weekly competition just text the word win to 80086 now. 18 t&c www.txttowin.co.uk', '100 dating service cal;l 09064012103 box334sk38ch', 'free ringtone text first to 87131 for a poly or text get to 87131 for a true tone! help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop', '4myths half price orange line rental & latest camera phones 4 free. had your phone 11myths ? call mobilesdirect free on 08000938767 to update now! or2stoptxt', 'double mins and texts 4 6months free bluetooth on orange. available on sony, nokia motorola phones. call mobileupd8 on 08000839402 or call2output/n9dx', 'thanks for your ringtone order, reference t91. you will be charged gb 4 per week. you can subscribe at anytime by calling customer services on 09057039994', 'here is your discount code rp176781. to stop further messages reply stop. www.regalportfolio.co.uk. customer services 08717205546', 'update_now - mas offer! latest motorola, sonyericsson & nokia & free bluetooth! double mins & 1000 txt on orange. call mobileupd8 on 08000839402 or call2output/f4q=', 'you are cash-balance is currently 500 pounds - to maximize you are cash-in now send cash to 86688 only 150p/message. cc: 08708800282 hg/suite342/2lands row/w1j6hl', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns www.dew.com1win150ppm3age16', 'fancy a sha? i do.interested? sextextuk.com txt uk szy to 69876. texts cost 1.50 per message. tns on website. x', 'valentines day special! win over £1000 in our quiz and take your partner on the trip of a lifetime! send go to 83600 now. 150p/message rcid. custard:08718720201.', 'call germany for only 1 pence per minute! call from a fixed line via access number 0844 861 85 85. no repayment. direct access!', 'december only! had your mobile 11myths+? you are entitled to update to the latest colour camera mobile for free! call the mobile update co free on 08002986906', 'think you are smart ? win £200 this week in our weekly quiz, text play to 85222 now!t&cs winnersclub po box 84, m26 3uz. 16+. gb1.50/week', 'them> check out our newest selection of content, games, tones, gossip, bases and sport, keep your mobile fit and funky text wap to 82468', 'sms. ac blind date 4u!: roads1 is 21/m from aberdeen, united kingdom. check him out http://img. sms. ac/w/icb3city8r7!-4 no blind dates send hide', "t-mobile customer you may now claim your free camera phone upgrade & a pay & go sim card for your loyalty. call on 0845 021 3680.offer ends 28the.t&c's apply", 'hmv bonus special 500 pounds of genuine hmv vouchers to be won. just answer 4 easy questions. play now! send hmv to 86688 more info:www.100percent-real.com', 'ringtone club: get the uk singles chart on your mobile each week and choose any top quality ringtone! this message is free of charge.', 'you are ringtone service has changed! 25 free credits! go to club4mobiles.com to choose content now! stop? txt club stop to 87070. 150p/wk club4 po box1146 mk45 2wt', 'hey i am really horn want to chat or see me naked text hot to 69698 text charged at 150pm to subscribe text stop 69698', 'we tried to contact you re your reply to our offer of a video handset? 750 anytime networks mins? unlimited text? camcorder? reply or call 08000930705 now', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns www.dew.com1win150ppm3age16', 'you 447801259231 have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09058094597', 'text & meet someone sexy today. you can find a date or even flirt its up to you. join 4 just 10p. reply with name & age eg sam 25. 18 -message red@thirtyeight pence', 'will you meet you are dream partner soon? is you are career off 2 a flying start? 2 find out free, txt hero followed by you are star sign, e. g. hero tries', '500 new mobiles from 2004, must go! txt: nokia to no: 89545 & collect yours today!from only £1 www.4-tc.biz 2output 087187262701.50gb/msg18', 'are you unique enough? find out from 30th august. www.areyouunique.co.uk', 'please call our customer service representative on freephone 0808 145 4742 between 9am-11pm as you have won a guaranteed £1000 cash or £5000 prize!', 'urgent! we are trying to contact you. last weekends draw shows that you have won a £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs only', 'bangbabes you are order is on the way. you should receive a service message 2 download you are content. if you do not, goto wap. bang. tv on you are mobile internet/service menu', '-pls stop bootydelious (32/f) is inviting you to be her friend. reply yes-434 or no-434 see her: www.sms.ac/you/bootydelious stop? send stop find to 62468', 'you are a winner you have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810', 'customer service announcement. you have a new years delivery waiting for you. please call 07046744435 now to arrange delivery', 'frees why have not you replied to my text? i am randy, sexy, female and live local. love to hear from you. netcollex ltd 08700621170150p per message reply stop to end', 'you will not rev any more msg from the chat svc. for free hardcore services text go to: 69988 if you get nothing you must age verify with yr network & try again', "want 2 get laid tonight? want real logging locations sent direct 2 you are mob? join the uk's largest logging network bt texting gravel to 69888! nt. ec2a. 31p.message@150p", 'sunshine quiz only q! win a top sony dvd player if you know which country the algae is in? txt ans to 82277. £1.50 sp:throne', 'todays vida numbers ending 7548 are selected to receive a $350 award. if you have a match please call 08712300220 quoting claim code 4041 standard rates app', 'urgent! your mobile no. was awarded £2000 bonus caller prize on 5/9/03 this is our final try to contact you! call from landing 09064019788 box42wr29c, 150ppm', 'private! your 2004 account statement for 07742676969 shows 786 redeemed bonus points. to claim call 08719180248 identifier code: 45239 expires', 'you are a winner you have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ', 'gent! we are trying to contact you. last weekends draw shows that you won a £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm', 'please call our customer service representative on 0800 169 6031 between 10am-9pm as you have won a guaranteed £1000 cash or £5000 prize!', 'did you hear about the new "divorce bare"? it comes with all of ken\'s stuff!', 'urgent you are awarded a complimentary trip to eurodisinc trap, aco&entry41 or £1000. to claim txt dis to 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj', 'as a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £1500 bonus prize, call 09066364589', 'contrast! 1 year special cinema pass for 2 is yours. call 09061209465 now! c superman v, matrix3, starwars3, etc all 4 free! bx420-ip4-5we. 150pm. do not miss out! ', 'sms. ac iptv: the new jersey devils and the detroit red wings play ice hockey. correct or incorrect? end? reply end iptv', '07732584351 - roger burns - message = we tried to call you re your reply to our sms for a free nokia mobile + free camcorder. please call now 08000930705 for delivery tomorrow', 'thanks for your subscription to ringtone uk your mobile will be charged £5/month please confirm by replying yes or no. if you reply no you will not be charged', 'england v macedonia - do not miss the goals/team news. txt you are national team to 87077 eg england to 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+', 'xxxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=qjkgighjjgcbl', 'urgent! you have won a 1 week free membership in our £100,000 prize jackpot! txt the word: claim to no: 81010 t&c www.duk.net lccltd box 4403link1a7rw18', 'six chances to win cash! from 100 to 20,000 pounds txt> cs11 and send to 87575. cost 150p/day, 6days, 16+ stands apply reply hl 4 info', 'had your mobile 11 months or more? you r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on 08002986030', 'winner!! as a valued network customer you have been selected to received £900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.', "frees hey there darling it is been 3 week's now and no word back! i would like some fun you up for it still? tb ok! xxx std chg to send, £1.50 to rev", "free entry in 2 a only comp to win fa cup final kts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's", 'y de asking like this.', 'we live in the next  &lt;#&gt; mins', 'been running but only managed 5 minutes and then needed oxygen! might have to resort to the roller option!', 'oh... haha... den we sold had went today too... gee, nevermind la... kai, i dun mind going jazz oso... scared hiphop open cannot catch up... ', 'i need an 8th but i am off campus atm, could i pick up in an hour or two?', 'than 4 putting da font down on me!!', 'and i do not plan on staying the night but i probably will not be back til late', 'hey j! r you feeling any better, hopes funny. i now feeling ill & think i may have tonsolitusaswell! damn iam latin in federal bored. lots love me xxxx', 'frees: txt: call to no: 86888 & claim your reward of 3 hours talk time to use from your phone now! subscribe6gb/math inc 3hrs 16 stop?txtstop', 'hi did you decide wot 2 get 4 his birthday if not ill pro jus get him a voucher frm virgin or surfing ', 'have you laid your airtel line to rest?', 'i am stuck in da middle of da row on da right hand side of da lt... ', 'full heat pa:-) i have applied oil pa.', 'carlos is down but i have to pick it up from him, so i will swing by usf in a little bit', 'yo sorry was in the shower sup', 'i had a good time too. its nice to do something a bit different with my weekends for a change. see ya soon', 'it is ok i won b angry. message you aft i come home tonight.', 'right it was not you who phone it was someone with a number like yours!', 'well done england! get the official poly ringtone or colour flag on yer mobile! text tone or flag to 84199 now! opt-out txt eng stop. box39822 w111wx £1.50', 'tomorrow i am not going to theatre. . . so i can come wherever you call me. . . tell me where and when to come tomorrow', 'have you not finished work yet or something?', 'i wanted to wish you a happy new year and i wanted to talk to you about some legal advice to do with when gary and i split but in person. i will make a trip to tbo for that. i hope everything is good with you babe and i love ya :)', 'i will see if i can swing by in a bit, got some things to take care of here first', 'mile, age23, blonde, new in uk. i look sex with uk guys. if you like fun with me. text talk to 69866.18 . 30pp/txt 1st 5free. £1.50 increments. help08718728876', 'you have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09065171142-stops-08718727870150ppm', 'noooooooo please. last thing i need is stress. for once in your life be fair.', "for you are chance to win a £250 only shopping spree txt: shop to 80878. t's&c's www.txt-2-shop.com custard 08715705022, 1x150p/wk", 'wow did not think it was that common. i take it all back you are not a freak! unless you chop it off:-)', 'not course. only maths one day one chapter with in one month we can finish.', 'hi ....my engagement has been find on  &lt;#&gt; th of next month. i know its really shocking bt....hmm njan vilikkam....t ws al of a sun;-(.', 'no plans yet. what are you doing ?', 'urgent! call 09066350750 from your landing. your complimentary 4* biz holiday or 10,000 cash await collection sae t&cs po box 434 sk3 8wp 150 ppm 18+', 'had your contract mobile 11 months? latest motorola, nokia etc. all free! double mins & text on orange tariffs. text yes for rollback, no to remove from records', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066', 'not directly behind... about 4 rows behind ü...', ':( but your not here....', 'urgent! this is the 2nd attempt to contact you!you have won £1000call 09071512432 before 300603t&cbc4235wc1n3xx.callcost150ppmmobilesvary. max£7. 50', 'omg how did you know what i ate?', 'cha quiteamuzing that\x92school babe,propos in & cu cathen funny 4brekkie! love jen xxx. extra lrg portions 4 me please ', 'want to have a laugh? try chit-chat on your mobile now! logo by texting the word: chat and send it to no: 8883 cm po box 4217 london w1a 6zf 16+ 118p/message rcid', 'at what time should i come tomorrow', 'miya how is it going in sunny africa? hope you r akin a good time. give that big old silver back a big kiss from me.', 'but you were together so you should be thinking about him', 'should i buy him a blackberry bold 2 or torch. should i buy him new or used. let me know. plus are you saying i should buy the  &lt;#&gt; g wifi ipad. and what are you saying about the about the  &lt;#&gt; g?', 'honeydew said: *i am d sweets in d world* god laughed &amp; said: *wait,you hant met d person reading this message* moral: even god can crack jokes! gm+gn+ge+gn:)', 'tell me again what your address is', 'come around  &lt;decimal&gt; pm vkey..i am outside nw, il come by the time', 'how much you trying to get?', 'good afternoon my bottom. how goes that walking here and there day ? did you get that police abstract? are you still out and about? i wake and miss you babe', 'i am awake oh. what is up.', 'think + da. you wil do.', 'piss is talking is someone that realise you that point this at is it.(now read it backwards)', 'i am in hospital da. . i will return home in evening', 'getting rd to ship comp', '7 wonders in my world 7th you 6th you are style 5th you are smile 4th you are personality 3rd you are nature 2nd you are sms and 1st "you are lovely friendship"... good morning dear', 'try to do something dear. you read something for exams', 'sun ah... the may can if dun have anything on... the have to book e lesson... e plates is at orchard mrt you noe hor...  ', 'symptoms when you are in love: "1.you like listening songs 2.you get stopped where you see the name of your beloved 3.you will not get angry when your', 'great. have a safe trip. do not panic surrender all.']

In [14]:
# On sauvegarde le résultat de la Normalisation (minuscule + contractions + correction)
# dans une nouvelle colonne AVANT de passer au nettoyage du bruit (Noise Removal).
df["Case Normalization"] = list(text)
df[["Message_body", "Case Normalization"]].head()

,Message_body,Case Normalization
0,"UpgrdCentre Orange customer, you may now claim...","upgrdcentre orange customer, you may now claim..."
1,"Loan for any purpose £500 - £75,000. Homeowner...","loan for any purpose £500 - £75,000. homeowner..."
2,Congrats! Nokia 3650 video camera phone is you...,contrast! nokia 3650 video camera phone is you...
3,URGENT! Your Mobile number has been awarded wi...,urgent! your mobile number has been awarded wi...
4,Someone has contacted our dating service and e...,someone has contacted our dating service and e...

# NOISE REMOVAL

In [15]:
# Noise Removal (Removing numbers/digits, Punctuation & Special Characters,
# Handling double whitespace from text, and Removal of URLs)

# --- Removal of URLs ---
import re

combined_url_pattern = re.compile(r'https?://\S+|www\.\S+')

def remove_urls(text_list):
    # On supprime entièrement les URLs (comme dans l'exemple de l'énoncé)
    return [combined_url_pattern.sub(' ', message) for message in text_list]

# Application
text = remove_urls(text)

In [16]:
print(text)

["upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available", "loan for any purpose £500 - £75,000. homeowners + tenants welcome. have you been previously refused? we can still help. call free 0800 1956669 or text back 'help'", 'contrast! nokia 3650 video camera phone is your call 09066382422 calls cost 150ppm ave call 3mins vary from mobiles 16+ close 300603 post bcm4284 lon wc1n3xx', 'urgent! your mobile number has been awarded with a £2000 prize guaranteed. call 09058094455 from land line. claim 3030. valid 12hrs only', 'someone has contacted our dating service and entered your phone because they fancy you! to find out who it is call from a landing 09111032124 . box12n146tf150p', 'send a logo 2 you are lover - 2 names joined by a heart. txt love name1 name2 mono eg love adam eve 07123456789 to 87077 yahoo! box36504w45wq xeno 4 no ads 150p', 'free entry into our £250 weekly competition just text the word win to 80086 now. 18 t&c  ', '100 dating service cal;l 09064012103 box334sk38ch', 'free ringtone text first to 87131 for a poly or text get to 87131 for a true tone! help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop', '4myths half price orange line rental & latest camera phones 4 free. had your phone 11myths ? call mobilesdirect free on 08000938767 to update now! or2stoptxt', 'double mins and texts 4 6months free bluetooth on orange. available on sony, nokia motorola phones. call mobileupd8 on 08000839402 or call2output/n9dx', 'thanks for your ringtone order, reference t91. you will be charged gb 4 per week. you can subscribe at anytime by calling customer services on 09057039994', 'here is your discount code rp176781. to stop further messages reply stop.   customer services 08717205546', 'update_now - mas offer! latest motorola, sonyericsson & nokia & free bluetooth! double mins & 1000 txt on orange. call mobileupd8 on 08000839402 or call2output/f4q=', 'you are cash-balance is currently 500 pounds - to maximize you are cash-in now send cash to 86688 only 150p/message. cc: 08708800282 hg/suite342/2lands row/w1j6hl', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns  ', 'fancy a sha? i do.interested? sextextuk.com txt uk szy to 69876. texts cost 1.50 per message. tns on website. x', 'valentines day special! win over £1000 in our quiz and take your partner on the trip of a lifetime! send go to 83600 now. 150p/message rcid. custard:08718720201.', 'call germany for only 1 pence per minute! call from a fixed line via access number 0844 861 85 85. no repayment. direct access!', 'december only! had your mobile 11myths+? you are entitled to update to the latest colour camera mobile for free! call the mobile update co free on 08002986906', 'think you are smart ? win £200 this week in our weekly quiz, text play to 85222 now!t&cs winnersclub po box 84, m26 3uz. 16+. gb1.50/week', 'them> check out our newest selection of content, games, tones, gossip, bases and sport, keep your mobile fit and funky text wap to 82468', 'sms. ac blind date 4u!: roads1 is 21/m from aberdeen, united kingdom. check him out   sms. ac/w/icb3city8r7!-4 no blind dates send hide', "t-mobile customer you may now claim your free camera phone upgrade & a pay & go sim card for your loyalty. call on 0845 021 3680.offer ends 28the.t&c's apply", 'hmv bonus special 500 pounds of genuine hmv vouchers to be won. just answer 4 easy questions. play now! send hmv to 86688 more info: ', 'ringtone club: get the uk singles chart on your mobile each week and choose any top quality ringtone! this message is free of charge.', 'you are ringtone service has changed! 25 free credits! go to club4mobiles.com to choose content now! stop? txt club stop to 87070. 150p/wk club4 po box1146 mk45 2wt', 'hey i am really horn want to chat or see me naked text hot to 69698 text charged at 150pm to subscribe text stop 69698', 'we tried to contact you re your reply to our offer of a video handset? 750 anytime networks mins? unlimited text? camcorder? reply or call 08000930705 now', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns  ', 'you 447801259231 have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09058094597', 'text & meet someone sexy today. you can find a date or even flirt its up to you. join 4 just 10p. reply with name & age eg sam 25. 18 -message red@thirtyeight pence', 'will you meet you are dream partner soon? is you are career off 2 a flying start? 2 find out free, txt hero followed by you are star sign, e. g. hero tries', '500 new mobiles from 2004, must go! txt: nokia to no: 89545 & collect yours today!from only £1   2output 087187262701.50gb/msg18', 'are you unique enough? find out from 30th august.  ', 'please call our customer service representative on freephone 0808 145 4742 between 9am-11pm as you have won a guaranteed £1000 cash or £5000 prize!', 'urgent! we are trying to contact you. last weekends draw shows that you have won a £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs only', 'bangbabes you are order is on the way. you should receive a service message 2 download you are content. if you do not, goto wap. bang. tv on you are mobile internet/service menu', '-pls stop bootydelious (32/f) is inviting you to be her friend. reply yes-434 or no-434 see her:   stop? send stop find to 62468', 'you are a winner you have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810', 'customer service announcement. you have a new years delivery waiting for you. please call 07046744435 now to arrange delivery', 'frees why have not you replied to my text? i am randy, sexy, female and live local. love to hear from you. netcollex ltd 08700621170150p per message reply stop to end', 'you will not rev any more msg from the chat svc. for free hardcore services text go to: 69988 if you get nothing you must age verify with yr network & try again', "want 2 get laid tonight? want real logging locations sent direct 2 you are mob? join the uk's largest logging network bt texting gravel to 69888! nt. ec2a. 31p.message@150p", 'sunshine quiz only q! win a top sony dvd player if you know which country the algae is in? txt ans to 82277. £1.50 sp:throne', 'todays vida numbers ending 7548 are selected to receive a $350 award. if you have a match please call 08712300220 quoting claim code 4041 standard rates app', 'urgent! your mobile no. was awarded £2000 bonus caller prize on 5/9/03 this is our final try to contact you! call from landing 09064019788 box42wr29c, 150ppm', 'private! your 2004 account statement for 07742676969 shows 786 redeemed bonus points. to claim call 08719180248 identifier code: 45239 expires', 'you are a winner you have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ', 'gent! we are trying to contact you. last weekends draw shows that you won a £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm', 'please call our customer service representative on 0800 169 6031 between 10am-9pm as you have won a guaranteed £1000 cash or £5000 prize!', 'did you hear about the new "divorce bare"? it comes with all of ken\'s stuff!', 'urgent you are awarded a complimentary trip to eurodisinc trap, aco&entry41 or £1000. to claim txt dis to 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj', 'as a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £1500 bonus prize, call 09066364589', 'contrast! 1 year special cinema pass for 2 is yours. call 09061209465 now! c superman v, matrix3, starwars3, etc all 4 free! bx420-ip4-5we. 150pm. do not miss out! ', 'sms. ac iptv: the new jersey devils and the detroit red wings play ice hockey. correct or incorrect? end? reply end iptv', '07732584351 - roger burns - message = we tried to call you re your reply to our sms for a free nokia mobile + free camcorder. please call now 08000930705 for delivery tomorrow', 'thanks for your subscription to ringtone uk your mobile will be charged £5/month please confirm by replying yes or no. if you reply no you will not be charged', 'england v macedonia - do not miss the goals/team news. txt you are national team to 87077 eg england to 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+', 'xxxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>>   xxxmobilemovieclub.com?n=qjkgighjjgcbl', 'urgent! you have won a 1 week free membership in our £100,000 prize jackpot! txt the word: claim to no: 81010 t&c   lccltd box 4403link1a7rw18', 'six chances to win cash! from 100 to 20,000 pounds txt> cs11 and send to 87575. cost 150p/day, 6days, 16+ stands apply reply hl 4 info', 'had your mobile 11 months or more? you r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on 08002986030', 'winner!! as a valued network customer you have been selected to received £900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.', "frees hey there darling it is been 3 week's now and no word back! i would like some fun you up for it still? tb ok! xxx std chg to send, £1.50 to rev", "free entry in 2 a only comp to win fa cup final kts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's", 'y de asking like this.', 'we live in the next  &lt;#&gt; mins', 'been running but only managed 5 minutes and then needed oxygen! might have to resort to the roller option!', 'oh... haha... den we sold had went today too... gee, nevermind la... kai, i dun mind going jazz oso... scared hiphop open cannot catch up... ', 'i need an 8th but i am off campus atm, could i pick up in an hour or two?', 'than 4 putting da font down on me!!', 'and i do not plan on staying the night but i probably will not be back til late', 'hey j! r you feeling any better, hopes funny. i now feeling ill & think i may have tonsolitusaswell! damn iam latin in federal bored. lots love me xxxx', 'frees: txt: call to no: 86888 & claim your reward of 3 hours talk time to use from your phone now! subscribe6gb/math inc 3hrs 16 stop?txtstop', 'hi did you decide wot 2 get 4 his birthday if not ill pro jus get him a voucher frm virgin or surfing ', 'have you laid your airtel line to rest?', 'i am stuck in da middle of da row on da right hand side of da lt... ', 'full heat pa:-) i have applied oil pa.', 'carlos is down but i have to pick it up from him, so i will swing by usf in a little bit', 'yo sorry was in the shower sup', 'i had a good time too. its nice to do something a bit different with my weekends for a change. see ya soon', 'it is ok i won b angry. message you aft i come home tonight.', 'right it was not you who phone it was someone with a number like yours!', 'well done england! get the official poly ringtone or colour flag on yer mobile! text tone or flag to 84199 now! opt-out txt eng stop. box39822 w111wx £1.50', 'tomorrow i am not going to theatre. . . so i can come wherever you call me. . . tell me where and when to come tomorrow', 'have you not finished work yet or something?', 'i wanted to wish you a happy new year and i wanted to talk to you about some legal advice to do with when gary and i split but in person. i will make a trip to tbo for that. i hope everything is good with you babe and i love ya :)', 'i will see if i can swing by in a bit, got some things to take care of here first', 'mile, age23, blonde, new in uk. i look sex with uk guys. if you like fun with me. text talk to 69866.18 . 30pp/txt 1st 5free. £1.50 increments. help08718728876', 'you have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09065171142-stops-08718727870150ppm', 'noooooooo please. last thing i need is stress. for once in your life be fair.', "for you are chance to win a £250 only shopping spree txt: shop to 80878. t's&c's   custard 08715705022, 1x150p/wk", 'wow did not think it was that common. i take it all back you are not a freak! unless you chop it off:-)', 'not course. only maths one day one chapter with in one month we can finish.', 'hi ....my engagement has been find on  &lt;#&gt; th of next month. i know its really shocking bt....hmm njan vilikkam....t ws al of a sun;-(.', 'no plans yet. what are you doing ?', 'urgent! call 09066350750 from your landing. your complimentary 4* biz holiday or 10,000 cash await collection sae t&cs po box 434 sk3 8wp 150 ppm 18+', 'had your contract mobile 11 months? latest motorola, nokia etc. all free! double mins & text on orange tariffs. text yes for rollback, no to remove from records', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066', 'not directly behind... about 4 rows behind ü...', ':( but your not here....', 'urgent! this is the 2nd attempt to contact you!you have won £1000call 09071512432 before 300603t&cbc4235wc1n3xx.callcost150ppmmobilesvary. max£7. 50', 'omg how did you know what i ate?', 'cha quiteamuzing that\x92school babe,propos in & cu cathen funny 4brekkie! love jen xxx. extra lrg portions 4 me please ', 'want to have a laugh? try chit-chat on your mobile now! logo by texting the word: chat and send it to no: 8883 cm po box 4217 london w1a 6zf 16+ 118p/message rcid', 'at what time should i come tomorrow', 'miya how is it going in sunny africa? hope you r akin a good time. give that big old silver back a big kiss from me.', 'but you were together so you should be thinking about him', 'should i buy him a blackberry bold 2 or torch. should i buy him new or used. let me know. plus are you saying i should buy the  &lt;#&gt; g wifi ipad. and what are you saying about the about the  &lt;#&gt; g?', 'honeydew said: *i am d sweets in d world* god laughed &amp; said: *wait,you hant met d person reading this message* moral: even god can crack jokes! gm+gn+ge+gn:)', 'tell me again what your address is', 'come around  &lt;decimal&gt; pm vkey..i am outside nw, il come by the time', 'how much you trying to get?', 'good afternoon my bottom. how goes that walking here and there day ? did you get that police abstract? are you still out and about? i wake and miss you babe', 'i am awake oh. what is up.', 'think + da. you wil do.', 'piss is talking is someone that realise you that point this at is it.(now read it backwards)', 'i am in hospital da. . i will return home in evening', 'getting rd to ship comp', '7 wonders in my world 7th you 6th you are style 5th you are smile 4th you are personality 3rd you are nature 2nd you are sms and 1st "you are lovely friendship"... good morning dear', 'try to do something dear. you read something for exams', 'sun ah... the may can if dun have anything on... the have to book e lesson... e plates is at orchard mrt you noe hor...  ', 'symptoms when you are in love: "1.you like listening songs 2.you get stopped where you see the name of your beloved 3.you will not get angry when your', 'great. have a safe trip. do not panic surrender all.']

In [17]:
# Removing numbers / digits

def remove_numbers(text_list):
    # On supprime les chiffres (les lettres collées restent : "26th" -> "th")
    return [re.sub(r'\d+', '', message) for message in text_list]

In [18]:
text = remove_numbers(text)

In [19]:
# Removing Punctuation & Special Characters
import string

def remove_punctuation(text_list):
    # On garde uniquement les lettres et les espaces.
    # Ainsi "t&c's" -> "tcs", "opt-out" -> "optout" (comme dans l'exemple)
    return [re.sub(r'[^a-z\s]', '', message) for message in text_list]

text = remove_punctuation(text)


# Handling double / multiple whitespace
def remove_extra_whitespace(text_list):
    # On remplace toute suite d'espaces par un seul, puis on enlève les bords.
    return [re.sub(r'\s+', ' ', message).strip() for message in text_list]

text = remove_extra_whitespace(text)

# Le texte est maintenant entièrement nettoyé -> on sauvegarde la colonne "Noise Removal"
df["Noise Removal"] = list(text)
df[["Case Normalization", "Noise Removal"]].head()

,Case Normalization,Noise Removal
0,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...
1,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...
2,contrast! nokia 3650 video camera phone is you...,contrast nokia video camera phone is your call...
3,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...
4,someone has contacted our dating service and e...,someone has contacted our dating service and e...

# TOKENIZATION

In [20]:
# Tokenization : on découpe chaque message nettoyé en une liste de mots (tokens)
from nltk.tokenize import word_tokenize

# Les versions récentes de NLTK utilisent le modèle "punkt_tab"
try:
    nltk.data.find("tokenizers/punkt_tab")
except LookupError:
    nltk.download("punkt_tab")

def tokenize(text_list):
    return [word_tokenize(message) for message in text_list]

tokens = tokenize(text)

# On sauvegarde la liste de tokens dans la colonne "Tokenization"
df["Tokenization"] = tokens
print(tokens[0])

['upgrdcentre', 'orange', 'customer', 'you', 'may', 'now', 'claim', 'your', 'free', 'camera', 'phone', 'upgrade', 'for', 'your', 'loyalty', 'call', 'now', 'on', 'offer', 'ends', 'th', 'july', 'tcs', 'apply', 'optout', 'available']

# STOPWORDS REMOVAL

In [21]:
# Stopwords removal : on retire les mots vides (the, you, on, for, ...)
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(token_list):
    return [[w for w in toks if w not in stop_words] for toks in token_list]

tokens_no_stop = remove_stopwords(tokens)

df["Stopwords"] = tokens_no_stop
print(tokens_no_stop[0])

['upgrdcentre', 'orange', 'customer', 'may', 'claim', 'free', 'camera', 'phone', 'upgrade', 'loyalty', 'call', 'offer', 'ends', 'th', 'july', 'tcs', 'apply', 'optout', 'available']

# STEMMING & LEMMATIZATION

In [22]:
# Stemming (Porter) : on coupe les suffixes pour obtenir la racine (forme brute)
# Ex : "loyalty" -> "loyalti", "apply" -> "appli". On part de la colonne "Stopwords".
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

def stem_tokens(token_list):
    return [[stemmer.stem(w) for w in toks] for toks in token_list]

stems = stem_tokens(tokens_no_stop)

df["Stemming"] = stems
print(stems[0])

['upgrdcentr', 'orang', 'custom', 'may', 'claim', 'free', 'camera', 'phone', 'upgrad', 'loyalti', 'call', 'offer', 'end', 'th', 'juli', 'tc', 'appli', 'optout', 'avail']

In [23]:
# Lemmatization (spaCy) : on ramène chaque mot à sa forme de base / dictionnaire
# Ex : "ends" -> "end". On part aussi de la colonne "Stopwords".
import spacy

nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

def lemmatize_tokens(token_list):
    lemmas = []
    for toks in token_list:
        # On reconstruit une phrase pour donner du contexte au lemmatiseur,
        # puis on récupère le lemme de chaque token.
        doc = nlp(" ".join(toks))
        lemmas.append([token.lemma_ for token in doc])
    return lemmas

lemmas = lemmatize_tokens(tokens_no_stop)

df["Lemmatization"] = lemmas
print(lemmas[0])

['upgrdcentre', 'orange', 'customer', 'may', 'claim', 'free', 'camera', 'phone', 'upgrade', 'loyalty', 'call', 'offer', 'end', 'th', 'july', 'tcs', 'apply', 'optout', 'available']

# Construction du DataFrame final (9 colonnes) & sauvegarde

In [24]:
# --- Construction du DataFrame final : 9 colonnes ---
# On remet les colonnes dans l'ordre demandé par l'énoncé.
final_cols = [
    "S. No.", "Message_body", "Label",
    "Case Normalization", "Noise Removal",
    "Tokenization", "Stopwords", "Stemming", "Lemmatization",
]
df = df[final_cols]

# Sauvegarde du dataset prétraité (9 colonnes)
df.to_csv("SMS_test_preprocessed.csv", index=False)

print("Dimensions finales :", df.shape, "->", df.shape[1], "colonnes")
print("Colonnes :", list(df.columns))
df.head()

Dimensions finales : (125, 9) -> 9 colonnes
Colonnes : ['S. No.', 'Message_body', 'Label', 'Case Normalization', 'Noise Removal', 'Tokenization', 'Stopwords', 'Stemming', 'Lemmatization']

,S. No.,Message_body,Label,Case Normalization,Noise Removal,Tokenization,Stopwords,Stemming,Lemmatization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,...","[upgrdcentre, orange, customer, may, claim, fr...","[upgrdcentr, orang, custom, may, claim, free, ...","[upgrdcentre, orange, customer, may, claim, fr..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...,"[loan, for, any, purpose, homeowners, tenants,...","[loan, purpose, homeowners, tenants, welcome, ...","[loan, purpos, homeown, tenant, welcom, previo...","[loan, purpose, homeowner, tenant, welcome, pr..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,contrast! nokia 3650 video camera phone is you...,contrast nokia video camera phone is your call...,"[contrast, nokia, video, camera, phone, is, yo...","[contrast, nokia, video, camera, phone, call, ...","[contrast, nokia, video, camera, phone, call, ...","[contrast, nokia, video, camera, phone, call, ..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar...","[urgent, mobile, number, awarded, prize, guara...","[urgent, mobil, number, award, prize, guarante...","[urgent, mobile, number, award, prize, guarant..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contacted our dating service and e...,someone has contacted our dating service and e...,"[someone, has, contacted, our, dating, service...","[someone, contacted, dating, service, entered,...","[someon, contact, date, servic, enter, phone, ...","[someone, contact, date, service, enter, phone..."