In [8]:
# --- BIBLIOTHÈQUES STANDARDS (Python) ---
import re               # Pour les expressions régulières (supprimer les URLs)
import string           # Pour accéder à la liste complète de ponctuation

# --- NLP : PRÉTRAITEMENT & RACINISATION (NLTK) ---
import nltk             # La base pour la tokenization et les stopwords
from nltk.tokenize import word_tokenize        # Pour découper le texte en mots
from nltk.corpus import stopwords              # Pour filtrer les mots vides (the, is, etc.)
from nltk.stem.porter import PorterStemmer    # Pour le stemming (racinisation)

# --- NLP : ANALYSE AVANCÉE (spaCy & TextBlob) ---
import spacy            # Pour la lemmatisation et le tagging haute précision
from textblob import TextBlob # Pour l'analyse de sentiment et les corrections rapides

# --- OUTILS SPÉCIALISÉS ---
import inflect          # Pour convertir les chiffres (3) en mots (three)
import emoji            # Pour détecter et supprimer les emojis 

# Pour NLTK
nltk.download('punkt')      # Modèle de tokenisation
nltk.download('stopwords')  # Liste des mots vides

# Pour spaCy (à faire dans le terminal)
!pip install python3 -m spacy download en_core_web_sm

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lucas.fandinoperez\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lucas.fandinoperez\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package stopwords is already up-to-date!

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -m

In [9]:
import pandas as pd

df = pd.read_csv('SMS_test.csv', encoding='latin-1')

In [10]:


df.isnull().sum()

S. No.          0
Message_body    0
Label           0
dtype: int64

In [11]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S. No.        125 non-null    int64
 1   Message_body  125 non-null    str
 2   Label         125 non-null    str
dtypes: int64(1), str(2)
memory usage: 3.1 KB

           S. No.
count  125.000000
mean    63.000000
std     36.228442
min      1.000000
25%     32.000000
50%     63.000000
75%     94.000000
max    125.000000

In [12]:
df.head(10)

   S. No.                                       Message_body Label
0       1  UpgrdCentre Orange customer, you may now claim...  Spam
1       2  Loan for any purpose £500 - £75,000. Homeowner...  Spam
2       3  Congrats! Nokia 3650 video camera phone is you...  Spam
3       4  URGENT! Your Mobile number has been awarded wi...  Spam
4       5  Someone has contacted our dating service and e...  Spam
5       6  Send a logo 2 ur lover - 2 names joined by a h...  Spam
6       7  FREE entry into our £250 weekly competition ju...  Spam
7       8  100 dating service cal;l 09064012103 box334sk38ch  Spam
8       9  FREE RINGTONE text FIRST to 87131 for a poly o...  Spam
9      10  4mths half price Orange line rental & latest c...  Spam

In [13]:
messages = df["Message_body"]

messages.head()

0    UpgrdCentre Orange customer, you may now claim...
1    Loan for any purpose £500 - £75,000. Homeowner...
2    Congrats! Nokia 3650 video camera phone is you...
3    URGENT! Your Mobile number has been awarded wi...
4    Someone has contacted our dating service and e...
Name: Message_body, dtype: str

# Text Normalization (Lowercasing, Handling contractions, Spell schecking)

In [14]:
# Lowercasing

# on définit notre fonction lowercase
def text_lower(text):
    return text.str.lower()


# on utilise notre fct
text = text_lower(messages)

In [15]:
print(text)

# on check si TOUTE la colonne est déjà en minuscules
est_propre = text.equals(text.str.lower())
print(f"\nLa colonne est-elle totalement en minuscules ? {est_propre}")

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th ur style 5th...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when u are in love: "1.u like listeni...
124    great. have a safe trip. dont panic surrender ...
Name: Message_body, Length: 125, dtype: str

La colonne est-elle totalement en minuscules ? True

In [16]:
# dealing with contractions

import contractions

def fix_contractions(text):
    if not isinstance(text, str):
        return text
    
    expanded_text = contractions.fix(text)
    return expanded_text

text = fix_contractions(text)

In [17]:
print(text)

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th ur style 5th...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when u are in love: "1.u like listeni...
124    great. have a safe trip. dont panic surrender ...
Name: Message_body, Length: 125, dtype: str

In [18]:
def fix_contractions(text_list):
    return [contractions.fix(message) for message in text_list]


text = fix_contractions(text)
print(text[0]) # Devrait afficher "...you may now claim..."

upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available

In [19]:
# spell checking 
!pip install autocorrect
from autocorrect import Speller


def correct(text_list, lang="en"):
    "Correct spellin using autocorrect for english."
    spell = Speller(lang=lang)
    return [spell(message) for message in text_list]

text = correct(text)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: autocorrect in c:\users\lucas.fandinoperez\desktop\github\lucas.fandinoperez\nlp\nlpenv\lib\site-packages (2.6.1)

In [20]:
print(text)

["upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available", "loan for any purpose £500 - £75,000. homeowners + tenants welcome. have you been previously refused? we can still help. call free 0800 1956669 or text back 'help'", 'contrast! nokia 3650 video camera phone is your call 09066382422 calls cost 150ppm ave call 3mins vary from mobiles 16+ close 300603 post bcm4284 lon wc1n3xx', 'urgent! your mobile number has been awarded with a £2000 prize guaranteed. call 09058094455 from land line. claim 3030. valid 12hrs only', 'someone has contacted our dating service and entered your phone because they fancy you! to find out who it is call from a landing 09111032124 . box12n146tf150p', 'send a logo 2 you are lover - 2 names joined by a heart. txt love name1 name2 mono eg love adam eve 07123456789 to 87077 yahoo! box36504w45wq xeno 4 no ads 150p', 'free entry into our £250 weekly competition just text the word win to 80086 now. 18 t&c www.txttowin.co.uk', '100 dating service cal;l 09064012103 box334sk38ch', 'free ringtone text first to 87131 for a poly or text get to 87131 for a true tone! help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop', '4myths half price orange line rental & latest camera phones 4 free. had your phone 11myths ? call mobilesdirect free on 08000938767 to update now! or2stoptxt', 'double mins and texts 4 6months free bluetooth on orange. available on sony, nokia motorola phones. call mobileupd8 on 08000839402 or call2output/n9dx', 'thanks for your ringtone order, reference t91. you will be charged gb 4 per week. you can subscribe at anytime by calling customer services on 09057039994', 'here is your discount code rp176781. to stop further messages reply stop. www.regalportfolio.co.uk. customer services 08717205546', 'update_now - mas offer! latest motorola, sonyericsson & nokia & free bluetooth! double mins & 1000 txt on orange. call mobileupd8 on 08000839402 or call2output/f4q=', 'you are cash-balance is currently 500 pounds - to maximize you are cash-in now send cash to 86688 only 150p/message. cc: 08708800282 hg/suite342/2lands row/w1j6hl', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns www.dew.com1win150ppm3age16', 'fancy a sha? i do.interested? sextextuk.com txt uk szy to 69876. texts cost 1.50 per message. tns on website. x', 'valentines day special! win over £1000 in our quiz and take your partner on the trip of a lifetime! send go to 83600 now. 150p/message rcid. custard:08718720201.', 'call germany for only 1 pence per minute! call from a fixed line via access number 0844 861 85 85. no repayment. direct access!', 'december only! had your mobile 11myths+? you are entitled to update to the latest colour camera mobile for free! call the mobile update co free on 08002986906', 'think you are smart ? win £200 this week in our weekly quiz, text play to 85222 now!t&cs winnersclub po box 84, m26 3uz. 16+. gb1.50/week', 'them> check out our newest selection of content, games, tones, gossip, bases and sport, keep your mobile fit and funky text wap to 82468', 'sms. ac blind date 4u!: roads1 is 21/m from aberdeen, united kingdom. check him out http://img. sms. ac/w/icb3city8r7!-4 no blind dates send hide', "t-mobile customer you may now claim your free camera phone upgrade & a pay & go sim card for your loyalty. call on 0845 021 3680.offer ends 28the.t&c's apply", 'hmv bonus special 500 pounds of genuine hmv vouchers to be won. just answer 4 easy questions. play now! send hmv to 86688 more info:www.100percent-real.com', 'ringtone club: get the uk singles chart on your mobile each week and choose any top quality ringtone! this message is free of charge.', 'you are ringtone service has changed! 25 free credits! go to club4mobiles.com to choose content now! stop? txt club stop to 87070. 150p/wk club4 po box1146 mk45 2wt', 'hey i am really horn want to chat or see me naked text hot to 69698 text charged at 150pm to subscribe text stop 69698', 'we tried to contact you re your reply to our offer of a video handset? 750 anytime networks mins? unlimited text? camcorder? reply or call 08000930705 now', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns www.dew.com1win150ppm3age16', 'you 447801259231 have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09058094597', 'text & meet someone sexy today. you can find a date or even flirt its up to you. join 4 just 10p. reply with name & age eg sam 25. 18 -message red@thirtyeight pence', 'will you meet you are dream partner soon? is you are career off 2 a flying start? 2 find out free, txt hero followed by you are star sign, e. g. hero tries', '500 new mobiles from 2004, must go! txt: nokia to no: 89545 & collect yours today!from only £1 www.4-tc.biz 2output 087187262701.50gb/msg18', 'are you unique enough? find out from 30th august. www.areyouunique.co.uk', 'please call our customer service representative on freephone 0808 145 4742 between 9am-11pm as you have won a guaranteed £1000 cash or £5000 prize!', 'urgent! we are trying to contact you. last weekends draw shows that you have won a £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs only', 'bangbabes you are order is on the way. you should receive a service message 2 download you are content. if you do not, goto wap. bang. tv on you are mobile internet/service menu', '-pls stop bootydelious (32/f) is inviting you to be her friend. reply yes-434 or no-434 see her: www.sms.ac/you/bootydelious stop? send stop find to 62468', 'you are a winner you have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810', 'customer service announcement. you have a new years delivery waiting for you. please call 07046744435 now to arrange delivery', 'frees why have not you replied to my text? i am randy, sexy, female and live local. love to hear from you. netcollex ltd 08700621170150p per message reply stop to end', 'you will not rev any more msg from the chat svc. for free hardcore services text go to: 69988 if you get nothing you must age verify with yr network & try again', "want 2 get laid tonight? want real logging locations sent direct 2 you are mob? join the uk's largest logging network bt texting gravel to 69888! nt. ec2a. 31p.message@150p", 'sunshine quiz only q! win a top sony dvd player if you know which country the algae is in? txt ans to 82277. £1.50 sp:throne', 'todays vida numbers ending 7548 are selected to receive a $350 award. if you have a match please call 08712300220 quoting claim code 4041 standard rates app', 'urgent! your mobile no. was awarded £2000 bonus caller prize on 5/9/03 this is our final try to contact you! call from landing 09064019788 box42wr29c, 150ppm', 'private! your 2004 account statement for 07742676969 shows 786 redeemed bonus points. to claim call 08719180248 identifier code: 45239 expires', 'you are a winner you have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ', 'gent! we are trying to contact you. last weekends draw shows that you won a £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm', 'please call our customer service representative on 0800 169 6031 between 10am-9pm as you have won a guaranteed £1000 cash or £5000 prize!', 'did you hear about the new "divorce bare"? it comes with all of ken\'s stuff!', 'urgent you are awarded a complimentary trip to eurodisinc trap, aco&entry41 or £1000. to claim txt dis to 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj', 'as a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £1500 bonus prize, call 09066364589', 'contrast! 1 year special cinema pass for 2 is yours. call 09061209465 now! c superman v, matrix3, starwars3, etc all 4 free! bx420-ip4-5we. 150pm. do not miss out! ', 'sms. ac iptv: the new jersey devils and the detroit red wings play ice hockey. correct or incorrect? end? reply end iptv', '07732584351 - roger burns - message = we tried to call you re your reply to our sms for a free nokia mobile + free camcorder. please call now 08000930705 for delivery tomorrow', 'thanks for your subscription to ringtone uk your mobile will be charged £5/month please confirm by replying yes or no. if you reply no you will not be charged', 'england v macedonia - do not miss the goals/team news. txt you are national team to 87077 eg england to 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+', 'xxxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=qjkgighjjgcbl', 'urgent! you have won a 1 week free membership in our £100,000 prize jackpot! txt the word: claim to no: 81010 t&c www.duk.net lccltd box 4403link1a7rw18', 'six chances to win cash! from 100 to 20,000 pounds txt> cs11 and send to 87575. cost 150p/day, 6days, 16+ stands apply reply hl 4 info', 'had your mobile 11 months or more? you r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on 08002986030', 'winner!! as a valued network customer you have been selected to received £900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.', "frees hey there darling it is been 3 week's now and no word back! i would like some fun you up for it still? tb ok! xxx std chg to send, £1.50 to rev", "free entry in 2 a only comp to win fa cup final kts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's", 'y de asking like this.', 'we live in the next  &lt;#&gt; mins', 'been running but only managed 5 minutes and then needed oxygen! might have to resort to the roller option!', 'oh... haha... den we sold had went today too... gee, nevermind la... kai, i dun mind going jazz oso... scared hiphop open cannot catch up... ', 'i need an 8th but i am off campus atm, could i pick up in an hour or two?', 'than 4 putting da font down on me!!', 'and i do not plan on staying the night but i probably will not be back til late', 'hey j! r you feeling any better, hopes funny. i now feeling ill & think i may have tonsolitusaswell! damn iam latin in federal bored. lots love me xxxx', 'frees: txt: call to no: 86888 & claim your reward of 3 hours talk time to use from your phone now! subscribe6gb/math inc 3hrs 16 stop?txtstop', 'hi did you decide wot 2 get 4 his birthday if not ill pro jus get him a voucher frm virgin or surfing ', 'have you laid your airtel line to rest?', 'i am stuck in da middle of da row on da right hand side of da lt... ', 'full heat pa:-) i have applied oil pa.', 'carlos is down but i have to pick it up from him, so i will swing by usf in a little bit', 'yo sorry was in the shower sup', 'i had a good time too. its nice to do something a bit different with my weekends for a change. see ya soon', 'it is ok i won b angry. message you aft i come home tonight.', 'right it was not you who phone it was someone with a number like yours!', 'well done england! get the official poly ringtone or colour flag on yer mobile! text tone or flag to 84199 now! opt-out txt eng stop. box39822 w111wx £1.50', 'tomorrow i am not going to theatre. . . so i can come wherever you call me. . . tell me where and when to come tomorrow', 'have you not finished work yet or something?', 'i wanted to wish you a happy new year and i wanted to talk to you about some legal advice to do with when gary and i split but in person. i will make a trip to tbo for that. i hope everything is good with you babe and i love ya :)', 'i will see if i can swing by in a bit, got some things to take care of here first', 'mile, age23, blonde, new in uk. i look sex with uk guys. if you like fun with me. text talk to 69866.18 . 30pp/txt 1st 5free. £1.50 increments. help08718728876', 'you have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09065171142-stops-08718727870150ppm', 'noooooooo please. last thing i need is stress. for once in your life be fair.', "for you are chance to win a £250 only shopping spree txt: shop to 80878. t's&c's www.txt-2-shop.com custard 08715705022, 1x150p/wk", 'wow did not think it was that common. i take it all back you are not a freak! unless you chop it off:-)', 'not course. only maths one day one chapter with in one month we can finish.', 'hi ....my engagement has been find on  &lt;#&gt; th of next month. i know its really shocking bt....hmm njan vilikkam....t ws al of a sun;-(.', 'no plans yet. what are you doing ?', 'urgent! call 09066350750 from your landing. your complimentary 4* biz holiday or 10,000 cash await collection sae t&cs po box 434 sk3 8wp 150 ppm 18+', 'had your contract mobile 11 months? latest motorola, nokia etc. all free! double mins & text on orange tariffs. text yes for rollback, no to remove from records', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066', 'not directly behind... about 4 rows behind ü...', ':( but your not here....', 'urgent! this is the 2nd attempt to contact you!you have won £1000call 09071512432 before 300603t&cbc4235wc1n3xx.callcost150ppmmobilesvary. max£7. 50', 'omg how did you know what i ate?', 'cha quiteamuzing that\x92school babe,propos in & cu cathen funny 4brekkie! love jen xxx. extra lrg portions 4 me please ', 'want to have a laugh? try chit-chat on your mobile now! logo by texting the word: chat and send it to no: 8883 cm po box 4217 london w1a 6zf 16+ 118p/message rcid', 'at what time should i come tomorrow', 'miya how is it going in sunny africa? hope you r akin a good time. give that big old silver back a big kiss from me.', 'but you were together so you should be thinking about him', 'should i buy him a blackberry bold 2 or torch. should i buy him new or used. let me know. plus are you saying i should buy the  &lt;#&gt; g wifi ipad. and what are you saying about the about the  &lt;#&gt; g?', 'honeydew said: *i am d sweets in d world* god laughed &amp; said: *wait,you hant met d person reading this message* moral: even god can crack jokes! gm+gn+ge+gn:)', 'tell me again what your address is', 'come around  &lt;decimal&gt; pm vkey..i am outside nw, il come by the time', 'how much you trying to get?', 'good afternoon my bottom. how goes that walking here and there day ? did you get that police abstract? are you still out and about? i wake and miss you babe', 'i am awake oh. what is up.', 'think + da. you wil do.', 'piss is talking is someone that realise you that point this at is it.(now read it backwards)', 'i am in hospital da. . i will return home in evening', 'getting rd to ship comp', '7 wonders in my world 7th you 6th you are style 5th you are smile 4th you are personality 3rd you are nature 2nd you are sms and 1st "you are lovely friendship"... good morning dear', 'try to do something dear. you read something for exams', 'sun ah... the may can if dun have anything on... the have to book e lesson... e plates is at orchard mrt you noe hor...  ', 'symptoms when you are in love: "1.you like listening songs 2.you get stopped where you see the name of your beloved 3.you will not get angry when your', 'great. have a safe trip. do not panic surrender all.']

# NOISE REMOVAL

In [21]:
### Noise Removal (Removing numbers/digits, Punctuation & Special Characters, Handling double whitespace from text, and Removal of URLs)

# removal of URLs
import re


combined_url_pattern = re.compile(r'https?://\S+|www\.\S+')

def remove_urls(text_list):
    
    return [combined_url_pattern.sub('<weblink>', message) for message in text_list]

# Application
text = remove_urls(text)

In [22]:
print(text)

["upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on 0207 153 9153. offer ends 26th july. t&c's apply. opt-out available", "loan for any purpose £500 - £75,000. homeowners + tenants welcome. have you been previously refused? we can still help. call free 0800 1956669 or text back 'help'", 'contrast! nokia 3650 video camera phone is your call 09066382422 calls cost 150ppm ave call 3mins vary from mobiles 16+ close 300603 post bcm4284 lon wc1n3xx', 'urgent! your mobile number has been awarded with a £2000 prize guaranteed. call 09058094455 from land line. claim 3030. valid 12hrs only', 'someone has contacted our dating service and entered your phone because they fancy you! to find out who it is call from a landing 09111032124 . box12n146tf150p', 'send a logo 2 you are lover - 2 names joined by a heart. txt love name1 name2 mono eg love adam eve 07123456789 to 87077 yahoo! box36504w45wq xeno 4 no ads 150p', 'free entry into our £250 weekly competition just text the word win to 80086 now. 18 t&c <weblink>', '100 dating service cal;l 09064012103 box334sk38ch', 'free ringtone text first to 87131 for a poly or text get to 87131 for a true tone! help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop', '4myths half price orange line rental & latest camera phones 4 free. had your phone 11myths ? call mobilesdirect free on 08000938767 to update now! or2stoptxt', 'double mins and texts 4 6months free bluetooth on orange. available on sony, nokia motorola phones. call mobileupd8 on 08000839402 or call2output/n9dx', 'thanks for your ringtone order, reference t91. you will be charged gb 4 per week. you can subscribe at anytime by calling customer services on 09057039994', 'here is your discount code rp176781. to stop further messages reply stop. <weblink> customer services 08717205546', 'update_now - mas offer! latest motorola, sonyericsson & nokia & free bluetooth! double mins & 1000 txt on orange. call mobileupd8 on 08000839402 or call2output/f4q=', 'you are cash-balance is currently 500 pounds - to maximize you are cash-in now send cash to 86688 only 150p/message. cc: 08708800282 hg/suite342/2lands row/w1j6hl', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns <weblink>', 'fancy a sha? i do.interested? sextextuk.com txt uk szy to 69876. texts cost 1.50 per message. tns on website. x', 'valentines day special! win over £1000 in our quiz and take your partner on the trip of a lifetime! send go to 83600 now. 150p/message rcid. custard:08718720201.', 'call germany for only 1 pence per minute! call from a fixed line via access number 0844 861 85 85. no repayment. direct access!', 'december only! had your mobile 11myths+? you are entitled to update to the latest colour camera mobile for free! call the mobile update co free on 08002986906', 'think you are smart ? win £200 this week in our weekly quiz, text play to 85222 now!t&cs winnersclub po box 84, m26 3uz. 16+. gb1.50/week', 'them> check out our newest selection of content, games, tones, gossip, bases and sport, keep your mobile fit and funky text wap to 82468', 'sms. ac blind date 4u!: roads1 is 21/m from aberdeen, united kingdom. check him out <weblink> sms. ac/w/icb3city8r7!-4 no blind dates send hide', "t-mobile customer you may now claim your free camera phone upgrade & a pay & go sim card for your loyalty. call on 0845 021 3680.offer ends 28the.t&c's apply", 'hmv bonus special 500 pounds of genuine hmv vouchers to be won. just answer 4 easy questions. play now! send hmv to 86688 more info:<weblink>', 'ringtone club: get the uk singles chart on your mobile each week and choose any top quality ringtone! this message is free of charge.', 'you are ringtone service has changed! 25 free credits! go to club4mobiles.com to choose content now! stop? txt club stop to 87070. 150p/wk club4 po box1146 mk45 2wt', 'hey i am really horn want to chat or see me naked text hot to 69698 text charged at 150pm to subscribe text stop 69698', 'we tried to contact you re your reply to our offer of a video handset? 750 anytime networks mins? unlimited text? camcorder? reply or call 08000930705 now', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066 tns <weblink>', 'you 447801259231 have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09058094597', 'text & meet someone sexy today. you can find a date or even flirt its up to you. join 4 just 10p. reply with name & age eg sam 25. 18 -message red@thirtyeight pence', 'will you meet you are dream partner soon? is you are career off 2 a flying start? 2 find out free, txt hero followed by you are star sign, e. g. hero tries', '500 new mobiles from 2004, must go! txt: nokia to no: 89545 & collect yours today!from only £1 <weblink> 2output 087187262701.50gb/msg18', 'are you unique enough? find out from 30th august. <weblink>', 'please call our customer service representative on freephone 0808 145 4742 between 9am-11pm as you have won a guaranteed £1000 cash or £5000 prize!', 'urgent! we are trying to contact you. last weekends draw shows that you have won a £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs only', 'bangbabes you are order is on the way. you should receive a service message 2 download you are content. if you do not, goto wap. bang. tv on you are mobile internet/service menu', '-pls stop bootydelious (32/f) is inviting you to be her friend. reply yes-434 or no-434 see her: <weblink> stop? send stop find to 62468', 'you are a winner you have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810', 'customer service announcement. you have a new years delivery waiting for you. please call 07046744435 now to arrange delivery', 'frees why have not you replied to my text? i am randy, sexy, female and live local. love to hear from you. netcollex ltd 08700621170150p per message reply stop to end', 'you will not rev any more msg from the chat svc. for free hardcore services text go to: 69988 if you get nothing you must age verify with yr network & try again', "want 2 get laid tonight? want real logging locations sent direct 2 you are mob? join the uk's largest logging network bt texting gravel to 69888! nt. ec2a. 31p.message@150p", 'sunshine quiz only q! win a top sony dvd player if you know which country the algae is in? txt ans to 82277. £1.50 sp:throne', 'todays vida numbers ending 7548 are selected to receive a $350 award. if you have a match please call 08712300220 quoting claim code 4041 standard rates app', 'urgent! your mobile no. was awarded £2000 bonus caller prize on 5/9/03 this is our final try to contact you! call from landing 09064019788 box42wr29c, 150ppm', 'private! your 2004 account statement for 07742676969 shows 786 redeemed bonus points. to claim call 08719180248 identifier code: 45239 expires', 'you are a winner you have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ', 'gent! we are trying to contact you. last weekends draw shows that you won a £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm', 'please call our customer service representative on 0800 169 6031 between 10am-9pm as you have won a guaranteed £1000 cash or £5000 prize!', 'did you hear about the new "divorce bare"? it comes with all of ken\'s stuff!', 'urgent you are awarded a complimentary trip to eurodisinc trap, aco&entry41 or £1000. to claim txt dis to 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj', 'as a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £1500 bonus prize, call 09066364589', 'contrast! 1 year special cinema pass for 2 is yours. call 09061209465 now! c superman v, matrix3, starwars3, etc all 4 free! bx420-ip4-5we. 150pm. do not miss out! ', 'sms. ac iptv: the new jersey devils and the detroit red wings play ice hockey. correct or incorrect? end? reply end iptv', '07732584351 - roger burns - message = we tried to call you re your reply to our sms for a free nokia mobile + free camcorder. please call now 08000930705 for delivery tomorrow', 'thanks for your subscription to ringtone uk your mobile will be charged £5/month please confirm by replying yes or no. if you reply no you will not be charged', 'england v macedonia - do not miss the goals/team news. txt you are national team to 87077 eg england to 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+', 'xxxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>> <weblink> xxxmobilemovieclub.com?n=qjkgighjjgcbl', 'urgent! you have won a 1 week free membership in our £100,000 prize jackpot! txt the word: claim to no: 81010 t&c <weblink> lccltd box 4403link1a7rw18', 'six chances to win cash! from 100 to 20,000 pounds txt> cs11 and send to 87575. cost 150p/day, 6days, 16+ stands apply reply hl 4 info', 'had your mobile 11 months or more? you r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on 08002986030', 'winner!! as a valued network customer you have been selected to received £900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.', "frees hey there darling it is been 3 week's now and no word back! i would like some fun you up for it still? tb ok! xxx std chg to send, £1.50 to rev", "free entry in 2 a only comp to win fa cup final kts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's", 'y de asking like this.', 'we live in the next  &lt;#&gt; mins', 'been running but only managed 5 minutes and then needed oxygen! might have to resort to the roller option!', 'oh... haha... den we sold had went today too... gee, nevermind la... kai, i dun mind going jazz oso... scared hiphop open cannot catch up... ', 'i need an 8th but i am off campus atm, could i pick up in an hour or two?', 'than 4 putting da font down on me!!', 'and i do not plan on staying the night but i probably will not be back til late', 'hey j! r you feeling any better, hopes funny. i now feeling ill & think i may have tonsolitusaswell! damn iam latin in federal bored. lots love me xxxx', 'frees: txt: call to no: 86888 & claim your reward of 3 hours talk time to use from your phone now! subscribe6gb/math inc 3hrs 16 stop?txtstop', 'hi did you decide wot 2 get 4 his birthday if not ill pro jus get him a voucher frm virgin or surfing ', 'have you laid your airtel line to rest?', 'i am stuck in da middle of da row on da right hand side of da lt... ', 'full heat pa:-) i have applied oil pa.', 'carlos is down but i have to pick it up from him, so i will swing by usf in a little bit', 'yo sorry was in the shower sup', 'i had a good time too. its nice to do something a bit different with my weekends for a change. see ya soon', 'it is ok i won b angry. message you aft i come home tonight.', 'right it was not you who phone it was someone with a number like yours!', 'well done england! get the official poly ringtone or colour flag on yer mobile! text tone or flag to 84199 now! opt-out txt eng stop. box39822 w111wx £1.50', 'tomorrow i am not going to theatre. . . so i can come wherever you call me. . . tell me where and when to come tomorrow', 'have you not finished work yet or something?', 'i wanted to wish you a happy new year and i wanted to talk to you about some legal advice to do with when gary and i split but in person. i will make a trip to tbo for that. i hope everything is good with you babe and i love ya :)', 'i will see if i can swing by in a bit, got some things to take care of here first', 'mile, age23, blonde, new in uk. i look sex with uk guys. if you like fun with me. text talk to 69866.18 . 30pp/txt 1st 5free. £1.50 increments. help08718728876', 'you have a secret admirer who is looking 2 make contact with you-find out who they r*reveal who thinks you are so special-call on 09065171142-stops-08718727870150ppm', 'noooooooo please. last thing i need is stress. for once in your life be fair.', "for you are chance to win a £250 only shopping spree txt: shop to 80878. t's&c's <weblink> custard 08715705022, 1x150p/wk", 'wow did not think it was that common. i take it all back you are not a freak! unless you chop it off:-)', 'not course. only maths one day one chapter with in one month we can finish.', 'hi ....my engagement has been find on  &lt;#&gt; th of next month. i know its really shocking bt....hmm njan vilikkam....t ws al of a sun;-(.', 'no plans yet. what are you doing ?', 'urgent! call 09066350750 from your landing. your complimentary 4* biz holiday or 10,000 cash await collection sae t&cs po box 434 sk3 8wp 150 ppm 18+', 'had your contract mobile 11 months? latest motorola, nokia etc. all free! double mins & text on orange tariffs. text yes for rollback, no to remove from records', 'congratulations you are awarded 500 of cd vouchers or 125gift guaranteed & free entry 2 100 only draw txt music to 87066', 'not directly behind... about 4 rows behind ü...', ':( but your not here....', 'urgent! this is the 2nd attempt to contact you!you have won £1000call 09071512432 before 300603t&cbc4235wc1n3xx.callcost150ppmmobilesvary. max£7. 50', 'omg how did you know what i ate?', 'cha quiteamuzing that\x92school babe,propos in & cu cathen funny 4brekkie! love jen xxx. extra lrg portions 4 me please ', 'want to have a laugh? try chit-chat on your mobile now! logo by texting the word: chat and send it to no: 8883 cm po box 4217 london w1a 6zf 16+ 118p/message rcid', 'at what time should i come tomorrow', 'miya how is it going in sunny africa? hope you r akin a good time. give that big old silver back a big kiss from me.', 'but you were together so you should be thinking about him', 'should i buy him a blackberry bold 2 or torch. should i buy him new or used. let me know. plus are you saying i should buy the  &lt;#&gt; g wifi ipad. and what are you saying about the about the  &lt;#&gt; g?', 'honeydew said: *i am d sweets in d world* god laughed &amp; said: *wait,you hant met d person reading this message* moral: even god can crack jokes! gm+gn+ge+gn:)', 'tell me again what your address is', 'come around  &lt;decimal&gt; pm vkey..i am outside nw, il come by the time', 'how much you trying to get?', 'good afternoon my bottom. how goes that walking here and there day ? did you get that police abstract? are you still out and about? i wake and miss you babe', 'i am awake oh. what is up.', 'think + da. you wil do.', 'piss is talking is someone that realise you that point this at is it.(now read it backwards)', 'i am in hospital da. . i will return home in evening', 'getting rd to ship comp', '7 wonders in my world 7th you 6th you are style 5th you are smile 4th you are personality 3rd you are nature 2nd you are sms and 1st "you are lovely friendship"... good morning dear', 'try to do something dear. you read something for exams', 'sun ah... the may can if dun have anything on... the have to book e lesson... e plates is at orchard mrt you noe hor...  ', 'symptoms when you are in love: "1.you like listening songs 2.you get stopped where you see the name of your beloved 3.you will not get angry when your', 'great. have a safe trip. do not panic surrender all.']

In [23]:
# removing numbers or digits

def remove_numbers(text_list):
    
    return [re.sub(r'\d+', '<masked number>', message) for message in text_list]

In [24]:
text = remove_numbers(text)

In [25]:
print(text)

["upgrdcentre orange customer, you may now claim your free camera phone upgrade for your loyalty. call now on <masked number> <masked number> <masked number>. offer ends <masked number>th july. t&c's apply. opt-out available", "loan for any purpose £<masked number> - £<masked number>,<masked number>. homeowners + tenants welcome. have you been previously refused? we can still help. call free <masked number> <masked number> or text back 'help'", 'contrast! nokia <masked number> video camera phone is your call <masked number> calls cost <masked number>ppm ave call <masked number>mins vary from mobiles <masked number>+ close <masked number> post bcm<masked number> lon wc<masked number>n<masked number>xx', 'urgent! your mobile number has been awarded with a £<masked number> prize guaranteed. call <masked number> from land line. claim <masked number>. valid <masked number>hrs only', 'someone has contacted our dating service and entered your phone because they fancy you! to find out who it is call from a landing <masked number> . box<masked number>n<masked number>tf<masked number>p', 'send a logo <masked number> you are lover - <masked number> names joined by a heart. txt love name<masked number> name<masked number> mono eg love adam eve <masked number> to <masked number> yahoo! box<masked number>w<masked number>wq xeno <masked number> no ads <masked number>p', 'free entry into our £<masked number> weekly competition just text the word win to <masked number> now. <masked number> t&c <weblink>', '<masked number> dating service cal;l <masked number> box<masked number>sk<masked number>ch', 'free ringtone text first to <masked number> for a poly or text get to <masked number> for a true tone! help? <masked number> <masked number> <masked number> after <masked number>st free, tones are <masked number>x£<masked number>pw to e£nd txt stop', '<masked number>myths half price orange line rental & latest camera phones <masked number> free. had your phone <masked number>myths ? call mobilesdirect free on <masked number> to update now! or<masked number>stoptxt', 'double mins and texts <masked number> <masked number>months free bluetooth on orange. available on sony, nokia motorola phones. call mobileupd<masked number> on <masked number> or call<masked number>output/n<masked number>dx', 'thanks for your ringtone order, reference t<masked number>. you will be charged gb <masked number> per week. you can subscribe at anytime by calling customer services on <masked number>', 'here is your discount code rp<masked number>. to stop further messages reply stop. <weblink> customer services <masked number>', 'update_now - mas offer! latest motorola, sonyericsson & nokia & free bluetooth! double mins & <masked number> txt on orange. call mobileupd<masked number> on <masked number> or call<masked number>output/f<masked number>q=', 'you are cash-balance is currently <masked number> pounds - to maximize you are cash-in now send cash to <masked number> only <masked number>p/message. cc: <masked number> hg/suite<masked number>/<masked number>lands row/w<masked number>j<masked number>hl', 'congratulations you are awarded <masked number> of cd vouchers or <masked number>gift guaranteed & free entry <masked number> <masked number> only draw txt music to <masked number> tns <weblink>', 'fancy a sha? i do.interested? sextextuk.com txt uk szy to <masked number>. texts cost <masked number>.<masked number> per message. tns on website. x', 'valentines day special! win over £<masked number> in our quiz and take your partner on the trip of a lifetime! send go to <masked number> now. <masked number>p/message rcid. custard:<masked number>.', 'call germany for only <masked number> pence per minute! call from a fixed line via access number <masked number> <masked number> <masked number> <masked number>. no repayment. direct access!', 'december only! had your mobile <masked number>myths+? you are entitled to update to the latest colour camera mobile for free! call the mobile update co free on <masked number>', 'think you are smart ? win £<masked number> this week in our weekly quiz, text play to <masked number> now!t&cs winnersclub po box <masked number>, m<masked number> <masked number>uz. <masked number>+. gb<masked number>.<masked number>/week', 'them> check out our newest selection of content, games, tones, gossip, bases and sport, keep your mobile fit and funky text wap to <masked number>', 'sms. ac blind date <masked number>u!: roads<masked number> is <masked number>/m from aberdeen, united kingdom. check him out <weblink> sms. ac/w/icb<masked number>city<masked number>r<masked number>!-<masked number> no blind dates send hide', "t-mobile customer you may now claim your free camera phone upgrade & a pay & go sim card for your loyalty. call on <masked number> <masked number> <masked number>.offer ends <masked number>the.t&c's apply", 'hmv bonus special <masked number> pounds of genuine hmv vouchers to be won. just answer <masked number> easy questions. play now! send hmv to <masked number> more info:<weblink>', 'ringtone club: get the uk singles chart on your mobile each week and choose any top quality ringtone! this message is free of charge.', 'you are ringtone service has changed! <masked number> free credits! go to club<masked number>mobiles.com to choose content now! stop? txt club stop to <masked number>. <masked number>p/wk club<masked number> po box<masked number> mk<masked number> <masked number>wt', 'hey i am really horn want to chat or see me naked text hot to <masked number> text charged at <masked number>pm to subscribe text stop <masked number>', 'we tried to contact you re your reply to our offer of a video handset? <masked number> anytime networks mins? unlimited text? camcorder? reply or call <masked number> now', 'congratulations you are awarded <masked number> of cd vouchers or <masked number>gift guaranteed & free entry <masked number> <masked number> only draw txt music to <masked number> tns <weblink>', 'you <masked number> have a secret admirer who is looking <masked number> make contact with you-find out who they r*reveal who thinks you are so special-call on <masked number>', 'text & meet someone sexy today. you can find a date or even flirt its up to you. join <masked number> just <masked number>p. reply with name & age eg sam <masked number>. <masked number> -message red@thirtyeight pence', 'will you meet you are dream partner soon? is you are career off <masked number> a flying start? <masked number> find out free, txt hero followed by you are star sign, e. g. hero tries', '<masked number> new mobiles from <masked number>, must go! txt: nokia to no: <masked number> & collect yours today!from only £<masked number> <weblink> <masked number>output <masked number>.<masked number>gb/msg<masked number>', 'are you unique enough? find out from <masked number>th august. <weblink>', 'please call our customer service representative on freephone <masked number> <masked number> <masked number> between <masked number>am-<masked number>pm as you have won a guaranteed £<masked number> cash or £<masked number> prize!', 'urgent! we are trying to contact you. last weekends draw shows that you have won a £<masked number> prize guaranteed. call <masked number>. claim code s<masked number>. valid <masked number>hrs only', 'bangbabes you are order is on the way. you should receive a service message <masked number> download you are content. if you do not, goto wap. bang. tv on you are mobile internet/service menu', '-pls stop bootydelious (<masked number>/f) is inviting you to be her friend. reply yes-<masked number> or no-<masked number> see her: <weblink> stop? send stop find to <masked number>', 'you are a winner you have been specially selected <masked number> receive £<masked number> cash or a <masked number>* holiday (flights inc) speak to a live operator <masked number> claim <masked number>', 'customer service announcement. you have a new years delivery waiting for you. please call <masked number> now to arrange delivery', 'frees why have not you replied to my text? i am randy, sexy, female and live local. love to hear from you. netcollex ltd <masked number>p per message reply stop to end', 'you will not rev any more msg from the chat svc. for free hardcore services text go to: <masked number> if you get nothing you must age verify with yr network & try again', "want <masked number> get laid tonight? want real logging locations sent direct <masked number> you are mob? join the uk's largest logging network bt texting gravel to <masked number>! nt. ec<masked number>a. <masked number>p.message@<masked number>p", 'sunshine quiz only q! win a top sony dvd player if you know which country the algae is in? txt ans to <masked number>. £<masked number>.<masked number> sp:throne', 'todays vida numbers ending <masked number> are selected to receive a $<masked number> award. if you have a match please call <masked number> quoting claim code <masked number> standard rates app', 'urgent! your mobile no. was awarded £<masked number> bonus caller prize on <masked number>/<masked number>/<masked number> this is our final try to contact you! call from landing <masked number> box<masked number>wr<masked number>c, <masked number>ppm', 'private! your <masked number> account statement for <masked number> shows <masked number> redeemed bonus points. to claim call <masked number> identifier code: <masked number> expires', 'you are a winner you have been specially selected <masked number> receive £<masked number> or a <masked number>* holiday (flights inc) speak to a live operator <masked number> claim <masked number>p/min (<masked number>+) ', 'gent! we are trying to contact you. last weekends draw shows that you won a £<masked number> prize guaranteed. call <masked number>. claim code k<masked number>. valid <masked number>hrs only. <masked number>ppm', 'please call our customer service representative on <masked number> <masked number> <masked number> between <masked number>am-<masked number>pm as you have won a guaranteed £<masked number> cash or £<masked number> prize!', 'did you hear about the new "divorce bare"? it comes with all of ken\'s stuff!', 'urgent you are awarded a complimentary trip to eurodisinc trap, aco&entry<masked number> or £<masked number>. to claim txt dis to <masked number> <masked number>+<masked number>*£<masked number>.<masked number>(morefrmmob. shracomorsglsuplt)<masked number>, ls<masked number> <masked number>aj', 'as a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £<masked number> bonus prize, call <masked number>', 'contrast! <masked number> year special cinema pass for <masked number> is yours. call <masked number> now! c superman v, matrix<masked number>, starwars<masked number>, etc all <masked number> free! bx<masked number>-ip<masked number>-<masked number>we. <masked number>pm. do not miss out! ', 'sms. ac iptv: the new jersey devils and the detroit red wings play ice hockey. correct or incorrect? end? reply end iptv', '<masked number> - roger burns - message = we tried to call you re your reply to our sms for a free nokia mobile + free camcorder. please call now <masked number> for delivery tomorrow', 'thanks for your subscription to ringtone uk your mobile will be charged £<masked number>/month please confirm by replying yes or no. if you reply no you will not be charged', 'england v macedonia - do not miss the goals/team news. txt you are national team to <masked number> eg england to <masked number> try:wales, scotland <masked number>txt/ú<masked number>.<masked number> poboxox<masked number>w<masked number>wq <masked number>+', 'xxxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>> <weblink> xxxmobilemovieclub.com?n=qjkgighjjgcbl', 'urgent! you have won a <masked number> week free membership in our £<masked number>,<masked number> prize jackpot! txt the word: claim to no: <masked number> t&c <weblink> lccltd box <masked number>link<masked number>a<masked number>rw<masked number>', 'six chances to win cash! from <masked number> to <masked number>,<masked number> pounds txt> cs<masked number> and send to <masked number>. cost <masked number>p/day, <masked number>days, <masked number>+ stands apply reply hl <masked number> info', 'had your mobile <masked number> months or more? you r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on <masked number>', 'winner!! as a valued network customer you have been selected to received £<masked number> prize reward! to claim call <masked number>. claim code kl<masked number>. valid <masked number> hours only.', "frees hey there darling it is been <masked number> week's now and no word back! i would like some fun you up for it still? tb ok! xxx std chg to send, £<masked number>.<masked number> to rev", "free entry in <masked number> a only comp to win fa cup final kts <masked number>st may <masked number>. text fa to <masked number> to receive entry question(std txt rate)t&c's apply <masked number>over<masked number>'s", 'y de asking like this.', 'we live in the next  &lt;#&gt; mins', 'been running but only managed <masked number> minutes and then needed oxygen! might have to resort to the roller option!', 'oh... haha... den we sold had went today too... gee, nevermind la... kai, i dun mind going jazz oso... scared hiphop open cannot catch up... ', 'i need an <masked number>th but i am off campus atm, could i pick up in an hour or two?', 'than <masked number> putting da font down on me!!', 'and i do not plan on staying the night but i probably will not be back til late', 'hey j! r you feeling any better, hopes funny. i now feeling ill & think i may have tonsolitusaswell! damn iam latin in federal bored. lots love me xxxx', 'frees: txt: call to no: <masked number> & claim your reward of <masked number> hours talk time to use from your phone now! subscribe<masked number>gb/math inc <masked number>hrs <masked number> stop?txtstop', 'hi did you decide wot <masked number> get <masked number> his birthday if not ill pro jus get him a voucher frm virgin or surfing ', 'have you laid your airtel line to rest?', 'i am stuck in da middle of da row on da right hand side of da lt... ', 'full heat pa:-) i have applied oil pa.', 'carlos is down but i have to pick it up from him, so i will swing by usf in a little bit', 'yo sorry was in the shower sup', 'i had a good time too. its nice to do something a bit different with my weekends for a change. see ya soon', 'it is ok i won b angry. message you aft i come home tonight.', 'right it was not you who phone it was someone with a number like yours!', 'well done england! get the official poly ringtone or colour flag on yer mobile! text tone or flag to <masked number> now! opt-out txt eng stop. box<masked number> w<masked number>wx £<masked number>.<masked number>', 'tomorrow i am not going to theatre. . . so i can come wherever you call me. . . tell me where and when to come tomorrow', 'have you not finished work yet or something?', 'i wanted to wish you a happy new year and i wanted to talk to you about some legal advice to do with when gary and i split but in person. i will make a trip to tbo for that. i hope everything is good with you babe and i love ya :)', 'i will see if i can swing by in a bit, got some things to take care of here first', 'mile, age<masked number>, blonde, new in uk. i look sex with uk guys. if you like fun with me. text talk to <masked number>.<masked number> . <masked number>pp/txt <masked number>st <masked number>free. £<masked number>.<masked number> increments. help<masked number>', 'you have a secret admirer who is looking <masked number> make contact with you-find out who they r*reveal who thinks you are so special-call on <masked number>-stops-<masked number>ppm', 'noooooooo please. last thing i need is stress. for once in your life be fair.', "for you are chance to win a £<masked number> only shopping spree txt: shop to <masked number>. t's&c's <weblink> custard <masked number>, <masked number>x<masked number>p/wk", 'wow did not think it was that common. i take it all back you are not a freak! unless you chop it off:-)', 'not course. only maths one day one chapter with in one month we can finish.', 'hi ....my engagement has been find on  &lt;#&gt; th of next month. i know its really shocking bt....hmm njan vilikkam....t ws al of a sun;-(.', 'no plans yet. what are you doing ?', 'urgent! call <masked number> from your landing. your complimentary <masked number>* biz holiday or <masked number>,<masked number> cash await collection sae t&cs po box <masked number> sk<masked number> <masked number>wp <masked number> ppm <masked number>+', 'had your contract mobile <masked number> months? latest motorola, nokia etc. all free! double mins & text on orange tariffs. text yes for rollback, no to remove from records', 'congratulations you are awarded <masked number> of cd vouchers or <masked number>gift guaranteed & free entry <masked number> <masked number> only draw txt music to <masked number>', 'not directly behind... about <masked number> rows behind ü...', ':( but your not here....', 'urgent! this is the <masked number>nd attempt to contact you!you have won £<masked number>call <masked number> before <masked number>t&cbc<masked number>wc<masked number>n<masked number>xx.callcost<masked number>ppmmobilesvary. max£<masked number>. <masked number>', 'omg how did you know what i ate?', 'cha quiteamuzing that\x92school babe,propos in & cu cathen funny <masked number>brekkie! love jen xxx. extra lrg portions <masked number> me please ', 'want to have a laugh? try chit-chat on your mobile now! logo by texting the word: chat and send it to no: <masked number> cm po box <masked number> london w<masked number>a <masked number>zf <masked number>+ <masked number>p/message rcid', 'at what time should i come tomorrow', 'miya how is it going in sunny africa? hope you r akin a good time. give that big old silver back a big kiss from me.', 'but you were together so you should be thinking about him', 'should i buy him a blackberry bold <masked number> or torch. should i buy him new or used. let me know. plus are you saying i should buy the  &lt;#&gt; g wifi ipad. and what are you saying about the about the  &lt;#&gt; g?', 'honeydew said: *i am d sweets in d world* god laughed &amp; said: *wait,you hant met d person reading this message* moral: even god can crack jokes! gm+gn+ge+gn:)', 'tell me again what your address is', 'come around  &lt;decimal&gt; pm vkey..i am outside nw, il come by the time', 'how much you trying to get?', 'good afternoon my bottom. how goes that walking here and there day ? did you get that police abstract? are you still out and about? i wake and miss you babe', 'i am awake oh. what is up.', 'think + da. you wil do.', 'piss is talking is someone that realise you that point this at is it.(now read it backwards)', 'i am in hospital da. . i will return home in evening', 'getting rd to ship comp', '<masked number> wonders in my world <masked number>th you <masked number>th you are style <masked number>th you are smile <masked number>th you are personality <masked number>rd you are nature <masked number>nd you are sms and <masked number>st "you are lovely friendship"... good morning dear', 'try to do something dear. you read something for exams', 'sun ah... the may can if dun have anything on... the have to book e lesson... e plates is at orchard mrt you noe hor...  ', 'symptoms when you are in love: "<masked number>.you like listening songs <masked number>.you get stopped where you see the name of your beloved <masked number>.you will not get angry when your', 'great. have a safe trip. do not panic surrender all.']

# tokenization

In [26]:
import nltk

# modèle de segmentation en phrases et mots
nltk.download('punkt')

# Si tu utilises une version très récente, ce paquet peut aussi être requis
nltk.download('punkt_tab')


def tokenize_text(text):
    # Découpe le texte en composants plus petits (tokens)
    return nltk.word_tokenize(text)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lucas.fandinoperez\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\lucas.fandinoperez\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package punkt_tab is already up-to-date!

In [29]:
tokenized = [tokenize_text(msg) for msg in text]
print("Result from tokenization:", tokenized)

Result from tokenization: [['upgrdcentre', 'orange', 'customer', ',', 'you', 'may', 'now', 'claim', 'your', 'free', 'camera', 'phone', 'upgrade', 'for', 'your', 'loyalty', '.', 'call', 'now', 'on', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.', 'offer', 'ends', '<', 'masked', 'number', '>', 'th', 'july', '.', 't', '&', 'c', "'s", 'apply', '.', 'opt-out', 'available'], ['loan', 'for', 'any', 'purpose', '£', '<', 'masked', 'number', '>', '-', '£', '<', 'masked', 'number', '>', ',', '<', 'masked', 'number', '>', '.', 'homeowners', '+', 'tenants', 'welcome', '.', 'have', 'you', 'been', 'previously', 'refused', '?', 'we', 'can', 'still', 'help', '.', 'call', 'free', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'or', 'text', 'back', "'help", "'"], ['contrast', '!', 'nokia', '<', 'masked', 'number', '>', 'video', 'camera', 'phone', 'is', 'your', 'call', '<', 'masked', 'number', '>', 'calls', 'cost', '<', 'masked', 'number', '>', 'ppm', 'ave', 'call', '<', 'masked', 'number', '>', 'mins', 'vary', 'from', 'mobiles', '<', 'masked', 'number', '>', '+', 'close', '<', 'masked', 'number', '>', 'post', 'bcm', '<', 'masked', 'number', '>', 'lon', 'wc', '<', 'masked', 'number', '>', 'n', '<', 'masked', 'number', '>', 'xx'], ['urgent', '!', 'your', 'mobile', 'number', 'has', 'been', 'awarded', 'with', 'a', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', 'from', 'land', 'line', '.', 'claim', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs', 'only'], ['someone', 'has', 'contacted', 'our', 'dating', 'service', 'and', 'entered', 'your', 'phone', 'because', 'they', 'fancy', 'you', '!', 'to', 'find', 'out', 'who', 'it', 'is', 'call', 'from', 'a', 'landing', '<', 'masked', 'number', '>', '.', 'box', '<', 'masked', 'number', '>', 'n', '<', 'masked', 'number', '>', 'tf', '<', 'masked', 'number', '>', 'p'], ['send', 'a', 'logo', '<', 'masked', 'number', '>', 'you', 'are', 'lover', '-', '<', 'masked', 'number', '>', 'names', 'joined', 'by', 'a', 'heart', '.', 'txt', 'love', 'name', '<', 'masked', 'number', '>', 'name', '<', 'masked', 'number', '>', 'mono', 'eg', 'love', 'adam', 'eve', '<', 'masked', 'number', '>', 'to', '<', 'masked', 'number', '>', 'yahoo', '!', 'box', '<', 'masked', 'number', '>', 'w', '<', 'masked', 'number', '>', 'wq', 'xeno', '<', 'masked', 'number', '>', 'no', 'ads', '<', 'masked', 'number', '>', 'p'], ['free', 'entry', 'into', 'our', '£', '<', 'masked', 'number', '>', 'weekly', 'competition', 'just', 'text', 'the', 'word', 'win', 'to', '<', 'masked', 'number', '>', 'now', '.', '<', 'masked', 'number', '>', 't', '&', 'c', '<', 'weblink', '>'], ['<', 'masked', 'number', '>', 'dating', 'service', 'cal', ';', 'l', '<', 'masked', 'number', '>', 'box', '<', 'masked', 'number', '>', 'sk', '<', 'masked', 'number', '>', 'ch'], ['free', 'ringtone', 'text', 'first', 'to', '<', 'masked', 'number', '>', 'for', 'a', 'poly', 'or', 'text', 'get', 'to', '<', 'masked', 'number', '>', 'for', 'a', 'true', 'tone', '!', 'help', '?', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'after', '<', 'masked', 'number', '>', 'st', 'free', ',', 'tones', 'are', '<', 'masked', 'number', '>', 'x£', '<', 'masked', 'number', '>', 'pw', 'to', 'e£nd', 'txt', 'stop'], ['<', 'masked', 'number', '>', 'myths', 'half', 'price', 'orange', 'line', 'rental', '&', 'latest', 'camera', 'phones', '<', 'masked', 'number', '>', 'free', '.', 'had', 'your', 'phone', '<', 'masked', 'number', '>', 'myths', '?', 'call', 'mobilesdirect', 'free', 'on', '<', 'masked', 'number', '>', 'to', 'update', 'now', '!', 'or', '<', 'masked', 'number', '>', 'stoptxt'], ['double', 'mins', 'and', 'texts', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'months', 'free', 'bluetooth', 'on', 'orange', '.', 'available', 'on', 'sony', ',', 'nokia', 'motorola', 'phones', '.', 'call', 'mobileupd', '<', 'masked', 'number', '>', 'on', '<', 'masked', 'number', '>', 'or', 'call', '<', 'masked', 'number', '>', 'output/n', '<', 'masked', 'number', '>', 'dx'], ['thanks', 'for', 'your', 'ringtone', 'order', ',', 'reference', 't', '<', 'masked', 'number', '>', '.', 'you', 'will', 'be', 'charged', 'gb', '<', 'masked', 'number', '>', 'per', 'week', '.', 'you', 'can', 'subscribe', 'at', 'anytime', 'by', 'calling', 'customer', 'services', 'on', '<', 'masked', 'number', '>'], ['here', 'is', 'your', 'discount', 'code', 'rp', '<', 'masked', 'number', '>', '.', 'to', 'stop', 'further', 'messages', 'reply', 'stop', '.', '<', 'weblink', '>', 'customer', 'services', '<', 'masked', 'number', '>'], ['update_now', '-', 'mas', 'offer', '!', 'latest', 'motorola', ',', 'sonyericsson', '&', 'nokia', '&', 'free', 'bluetooth', '!', 'double', 'mins', '&', '<', 'masked', 'number', '>', 'txt', 'on', 'orange', '.', 'call', 'mobileupd', '<', 'masked', 'number', '>', 'on', '<', 'masked', 'number', '>', 'or', 'call', '<', 'masked', 'number', '>', 'output/f', '<', 'masked', 'number', '>', 'q='], ['you', 'are', 'cash-balance', 'is', 'currently', '<', 'masked', 'number', '>', 'pounds', '-', 'to', 'maximize', 'you', 'are', 'cash-in', 'now', 'send', 'cash', 'to', '<', 'masked', 'number', '>', 'only', '<', 'masked', 'number', '>', 'p/message', '.', 'cc', ':', '<', 'masked', 'number', '>', 'hg/suite', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', 'lands', 'row/w', '<', 'masked', 'number', '>', 'j', '<', 'masked', 'number', '>', 'hl'], ['congratulations', 'you', 'are', 'awarded', '<', 'masked', 'number', '>', 'of', 'cd', 'vouchers', 'or', '<', 'masked', 'number', '>', 'gift', 'guaranteed', '&', 'free', 'entry', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'only', 'draw', 'txt', 'music', 'to', '<', 'masked', 'number', '>', 'tns', '<', 'weblink', '>'], ['fancy', 'a', 'sha', '?', 'i', 'do.interested', '?', 'sextextuk.com', 'txt', 'uk', 'szy', 'to', '<', 'masked', 'number', '>', '.', 'texts', 'cost', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'per', 'message', '.', 'tns', 'on', 'website', '.', 'x'], ['valentines', 'day', 'special', '!', 'win', 'over', '£', '<', 'masked', 'number', '>', 'in', 'our', 'quiz', 'and', 'take', 'your', 'partner', 'on', 'the', 'trip', 'of', 'a', 'lifetime', '!', 'send', 'go', 'to', '<', 'masked', 'number', '>', 'now', '.', '<', 'masked', 'number', '>', 'p/message', 'rcid', '.', 'custard', ':', '<', 'masked', 'number', '>', '.'], ['call', 'germany', 'for', 'only', '<', 'masked', 'number', '>', 'pence', 'per', 'minute', '!', 'call', 'from', 'a', 'fixed', 'line', 'via', 'access', 'number', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.', 'no', 'repayment', '.', 'direct', 'access', '!'], ['december', 'only', '!', 'had', 'your', 'mobile', '<', 'masked', 'number', '>', 'myths+', '?', 'you', 'are', 'entitled', 'to', 'update', 'to', 'the', 'latest', 'colour', 'camera', 'mobile', 'for', 'free', '!', 'call', 'the', 'mobile', 'update', 'co', 'free', 'on', '<', 'masked', 'number', '>'], ['think', 'you', 'are', 'smart', '?', 'win', '£', '<', 'masked', 'number', '>', 'this', 'week', 'in', 'our', 'weekly', 'quiz', ',', 'text', 'play', 'to', '<', 'masked', 'number', '>', 'now', '!', 't', '&', 'cs', 'winnersclub', 'po', 'box', '<', 'masked', 'number', '>', ',', 'm', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'uz', '.', '<', 'masked', 'number', '>', '+', '.', 'gb', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '/week'], ['them', '>', 'check', 'out', 'our', 'newest', 'selection', 'of', 'content', ',', 'games', ',', 'tones', ',', 'gossip', ',', 'bases', 'and', 'sport', ',', 'keep', 'your', 'mobile', 'fit', 'and', 'funky', 'text', 'wap', 'to', '<', 'masked', 'number', '>'], ['sms', '.', 'ac', 'blind', 'date', '<', 'masked', 'number', '>', 'u', '!', ':', 'roads', '<', 'masked', 'number', '>', 'is', '<', 'masked', 'number', '>', '/m', 'from', 'aberdeen', ',', 'united', 'kingdom', '.', 'check', 'him', 'out', '<', 'weblink', '>', 'sms', '.', 'ac/w/icb', '<', 'masked', 'number', '>', 'city', '<', 'masked', 'number', '>', 'r', '<', 'masked', 'number', '>', '!', '-', '<', 'masked', 'number', '>', 'no', 'blind', 'dates', 'send', 'hide'], ['t-mobile', 'customer', 'you', 'may', 'now', 'claim', 'your', 'free', 'camera', 'phone', 'upgrade', '&', 'a', 'pay', '&', 'go', 'sim', 'card', 'for', 'your', 'loyalty', '.', 'call', 'on', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.offer', 'ends', '<', 'masked', 'number', '>', 'the.t', '&', 'c', "'s", 'apply'], ['hmv', 'bonus', 'special', '<', 'masked', 'number', '>', 'pounds', 'of', 'genuine', 'hmv', 'vouchers', 'to', 'be', 'won', '.', 'just', 'answer', '<', 'masked', 'number', '>', 'easy', 'questions', '.', 'play', 'now', '!', 'send', 'hmv', 'to', '<', 'masked', 'number', '>', 'more', 'info', ':', '<', 'weblink', '>'], ['ringtone', 'club', ':', 'get', 'the', 'uk', 'singles', 'chart', 'on', 'your', 'mobile', 'each', 'week', 'and', 'choose', 'any', 'top', 'quality', 'ringtone', '!', 'this', 'message', 'is', 'free', 'of', 'charge', '.'], ['you', 'are', 'ringtone', 'service', 'has', 'changed', '!', '<', 'masked', 'number', '>', 'free', 'credits', '!', 'go', 'to', 'club', '<', 'masked', 'number', '>', 'mobiles.com', 'to', 'choose', 'content', 'now', '!', 'stop', '?', 'txt', 'club', 'stop', 'to', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'p/wk', 'club', '<', 'masked', 'number', '>', 'po', 'box', '<', 'masked', 'number', '>', 'mk', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'wt'], ['hey', 'i', 'am', 'really', 'horn', 'want', 'to', 'chat', 'or', 'see', 'me', 'naked', 'text', 'hot', 'to', '<', 'masked', 'number', '>', 'text', 'charged', 'at', '<', 'masked', 'number', '>', 'pm', 'to', 'subscribe', 'text', 'stop', '<', 'masked', 'number', '>'], ['we', 'tried', 'to', 'contact', 'you', 're', 'your', 'reply', 'to', 'our', 'offer', 'of', 'a', 'video', 'handset', '?', '<', 'masked', 'number', '>', 'anytime', 'networks', 'mins', '?', 'unlimited', 'text', '?', 'camcorder', '?', 'reply', 'or', 'call', '<', 'masked', 'number', '>', 'now'], ['congratulations', 'you', 'are', 'awarded', '<', 'masked', 'number', '>', 'of', 'cd', 'vouchers', 'or', '<', 'masked', 'number', '>', 'gift', 'guaranteed', '&', 'free', 'entry', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'only', 'draw', 'txt', 'music', 'to', '<', 'masked', 'number', '>', 'tns', '<', 'weblink', '>'], ['you', '<', 'masked', 'number', '>', 'have', 'a', 'secret', 'admirer', 'who', 'is', 'looking', '<', 'masked', 'number', '>', 'make', 'contact', 'with', 'you-find', 'out', 'who', 'they', 'r', '*', 'reveal', 'who', 'thinks', 'you', 'are', 'so', 'special-call', 'on', '<', 'masked', 'number', '>'], ['text', '&', 'meet', 'someone', 'sexy', 'today', '.', 'you', 'can', 'find', 'a', 'date', 'or', 'even', 'flirt', 'its', 'up', 'to', 'you', '.', 'join', '<', 'masked', 'number', '>', 'just', '<', 'masked', 'number', '>', 'p', '.', 'reply', 'with', 'name', '&', 'age', 'eg', 'sam', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '-message', 'red', '@', 'thirtyeight', 'pence'], ['will', 'you', 'meet', 'you', 'are', 'dream', 'partner', 'soon', '?', 'is', 'you', 'are', 'career', 'off', '<', 'masked', 'number', '>', 'a', 'flying', 'start', '?', '<', 'masked', 'number', '>', 'find', 'out', 'free', ',', 'txt', 'hero', 'followed', 'by', 'you', 'are', 'star', 'sign', ',', 'e.', 'g.', 'hero', 'tries'], ['<', 'masked', 'number', '>', 'new', 'mobiles', 'from', '<', 'masked', 'number', '>', ',', 'must', 'go', '!', 'txt', ':', 'nokia', 'to', 'no', ':', '<', 'masked', 'number', '>', '&', 'collect', 'yours', 'today', '!', 'from', 'only', '£', '<', 'masked', 'number', '>', '<', 'weblink', '>', '<', 'masked', 'number', '>', 'output', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'gb/msg', '<', 'masked', 'number', '>'], ['are', 'you', 'unique', 'enough', '?', 'find', 'out', 'from', '<', 'masked', 'number', '>', 'th', 'august', '.', '<', 'weblink', '>'], ['please', 'call', 'our', 'customer', 'service', 'representative', 'on', 'freephone', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'between', '<', 'masked', 'number', '>', 'am-', '<', 'masked', 'number', '>', 'pm', 'as', 'you', 'have', 'won', 'a', 'guaranteed', '£', '<', 'masked', 'number', '>', 'cash', 'or', '£', '<', 'masked', 'number', '>', 'prize', '!'], ['urgent', '!', 'we', 'are', 'trying', 'to', 'contact', 'you', '.', 'last', 'weekends', 'draw', 'shows', 'that', 'you', 'have', 'won', 'a', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', '.', 'claim', 'code', 's', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs', 'only'], ['bangbabes', 'you', 'are', 'order', 'is', 'on', 'the', 'way', '.', 'you', 'should', 'receive', 'a', 'service', 'message', '<', 'masked', 'number', '>', 'download', 'you', 'are', 'content', '.', 'if', 'you', 'do', 'not', ',', 'goto', 'wap', '.', 'bang', '.', 'tv', 'on', 'you', 'are', 'mobile', 'internet/service', 'menu'], ['-pls', 'stop', 'bootydelious', '(', '<', 'masked', 'number', '>', '/f', ')', 'is', 'inviting', 'you', 'to', 'be', 'her', 'friend', '.', 'reply', 'yes-', '<', 'masked', 'number', '>', 'or', 'no-', '<', 'masked', 'number', '>', 'see', 'her', ':', '<', 'weblink', '>', 'stop', '?', 'send', 'stop', 'find', 'to', '<', 'masked', 'number', '>'], ['you', 'are', 'a', 'winner', 'you', 'have', 'been', 'specially', 'selected', '<', 'masked', 'number', '>', 'receive', '£', '<', 'masked', 'number', '>', 'cash', 'or', 'a', '<', 'masked', 'number', '>', '*', 'holiday', '(', 'flights', 'inc', ')', 'speak', 'to', 'a', 'live', 'operator', '<', 'masked', 'number', '>', 'claim', '<', 'masked', 'number', '>'], ['customer', 'service', 'announcement', '.', 'you', 'have', 'a', 'new', 'years', 'delivery', 'waiting', 'for', 'you', '.', 'please', 'call', '<', 'masked', 'number', '>', 'now', 'to', 'arrange', 'delivery'], ['frees', 'why', 'have', 'not', 'you', 'replied', 'to', 'my', 'text', '?', 'i', 'am', 'randy', ',', 'sexy', ',', 'female', 'and', 'live', 'local', '.', 'love', 'to', 'hear', 'from', 'you', '.', 'netcollex', 'ltd', '<', 'masked', 'number', '>', 'p', 'per', 'message', 'reply', 'stop', 'to', 'end'], ['you', 'will', 'not', 'rev', 'any', 'more', 'msg', 'from', 'the', 'chat', 'svc', '.', 'for', 'free', 'hardcore', 'services', 'text', 'go', 'to', ':', '<', 'masked', 'number', '>', 'if', 'you', 'get', 'nothing', 'you', 'must', 'age', 'verify', 'with', 'yr', 'network', '&', 'try', 'again'], ['want', '<', 'masked', 'number', '>', 'get', 'laid', 'tonight', '?', 'want', 'real', 'logging', 'locations', 'sent', 'direct', '<', 'masked', 'number', '>', 'you', 'are', 'mob', '?', 'join', 'the', 'uk', "'s", 'largest', 'logging', 'network', 'bt', 'texting', 'gravel', 'to', '<', 'masked', 'number', '>', '!', 'nt', '.', 'ec', '<', 'masked', 'number', '>', 'a', '.', '<', 'masked', 'number', '>', 'p.message', '@', '<', 'masked', 'number', '>', 'p'], ['sunshine', 'quiz', 'only', 'q', '!', 'win', 'a', 'top', 'sony', 'dvd', 'player', 'if', 'you', 'know', 'which', 'country', 'the', 'algae', 'is', 'in', '?', 'txt', 'ans', 'to', '<', 'masked', 'number', '>', '.', '£', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'sp', ':', 'throne'], ['todays', 'vida', 'numbers', 'ending', '<', 'masked', 'number', '>', 'are', 'selected', 'to', 'receive', 'a', '$', '<', 'masked', 'number', '>', 'award', '.', 'if', 'you', 'have', 'a', 'match', 'please', 'call', '<', 'masked', 'number', '>', 'quoting', 'claim', 'code', '<', 'masked', 'number', '>', 'standard', 'rates', 'app'], ['urgent', '!', 'your', 'mobile', 'no', '.', 'was', 'awarded', '£', '<', 'masked', 'number', '>', 'bonus', 'caller', 'prize', 'on', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', 'this', 'is', 'our', 'final', 'try', 'to', 'contact', 'you', '!', 'call', 'from', 'landing', '<', 'masked', 'number', '>', 'box', '<', 'masked', 'number', '>', 'wr', '<', 'masked', 'number', '>', 'c', ',', '<', 'masked', 'number', '>', 'ppm'], ['private', '!', 'your', '<', 'masked', 'number', '>', 'account', 'statement', 'for', '<', 'masked', 'number', '>', 'shows', '<', 'masked', 'number', '>', 'redeemed', 'bonus', 'points', '.', 'to', 'claim', 'call', '<', 'masked', 'number', '>', 'identifier', 'code', ':', '<', 'masked', 'number', '>', 'expires'], ['you', 'are', 'a', 'winner', 'you', 'have', 'been', 'specially', 'selected', '<', 'masked', 'number', '>', 'receive', '£', '<', 'masked', 'number', '>', 'or', 'a', '<', 'masked', 'number', '>', '*', 'holiday', '(', 'flights', 'inc', ')', 'speak', 'to', 'a', 'live', 'operator', '<', 'masked', 'number', '>', 'claim', '<', 'masked', 'number', '>', 'p/min', '(', '<', 'masked', 'number', '>', '+', ')'], ['gent', '!', 'we', 'are', 'trying', 'to', 'contact', 'you', '.', 'last', 'weekends', 'draw', 'shows', 'that', 'you', 'won', 'a', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', '.', 'claim', 'code', 'k', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs', 'only', '.', '<', 'masked', 'number', '>', 'ppm'], ['please', 'call', 'our', 'customer', 'service', 'representative', 'on', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'between', '<', 'masked', 'number', '>', 'am-', '<', 'masked', 'number', '>', 'pm', 'as', 'you', 'have', 'won', 'a', 'guaranteed', '£', '<', 'masked', 'number', '>', 'cash', 'or', '£', '<', 'masked', 'number', '>', 'prize', '!'], ['did', 'you', 'hear', 'about', 'the', 'new', '``', 'divorce', 'bare', "''", '?', 'it', 'comes', 'with', 'all', 'of', 'ken', "'s", 'stuff', '!'], ['urgent', 'you', 'are', 'awarded', 'a', 'complimentary', 'trip', 'to', 'eurodisinc', 'trap', ',', 'aco', '&', 'entry', '<', 'masked', 'number', '>', 'or', '£', '<', 'masked', 'number', '>', '.', 'to', 'claim', 'txt', 'dis', 'to', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '+', '<', 'masked', 'number', '>', '*', '£', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '(', 'morefrmmob', '.', 'shracomorsglsuplt', ')', '<', 'masked', 'number', '>', ',', 'ls', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'aj'], ['as', 'a', 'valued', 'customer', ',', 'i', 'am', 'pleased', 'to', 'advise', 'you', 'that', 'following', 'recent', 'review', 'of', 'your', 'mob', 'no', '.', 'you', 'are', 'awarded', 'with', 'a', '£', '<', 'masked', 'number', '>', 'bonus', 'prize', ',', 'call', '<', 'masked', 'number', '>'], ['contrast', '!', '<', 'masked', 'number', '>', 'year', 'special', 'cinema', 'pass', 'for', '<', 'masked', 'number', '>', 'is', 'yours', '.', 'call', '<', 'masked', 'number', '>', 'now', '!', 'c', 'superman', 'v', ',', 'matrix', '<', 'masked', 'number', '>', ',', 'starwars', '<', 'masked', 'number', '>', ',', 'etc', 'all', '<', 'masked', 'number', '>', 'free', '!', 'bx', '<', 'masked', 'number', '>', '-ip', '<', 'masked', 'number', '>', '-', '<', 'masked', 'number', '>', 'we', '.', '<', 'masked', 'number', '>', 'pm', '.', 'do', 'not', 'miss', 'out', '!'], ['sms', '.', 'ac', 'iptv', ':', 'the', 'new', 'jersey', 'devils', 'and', 'the', 'detroit', 'red', 'wings', 'play', 'ice', 'hockey', '.', 'correct', 'or', 'incorrect', '?', 'end', '?', 'reply', 'end', 'iptv'], ['<', 'masked', 'number', '>', '-', 'roger', 'burns', '-', 'message', '=', 'we', 'tried', 'to', 'call', 'you', 're', 'your', 'reply', 'to', 'our', 'sms', 'for', 'a', 'free', 'nokia', 'mobile', '+', 'free', 'camcorder', '.', 'please', 'call', 'now', '<', 'masked', 'number', '>', 'for', 'delivery', 'tomorrow'], ['thanks', 'for', 'your', 'subscription', 'to', 'ringtone', 'uk', 'your', 'mobile', '

# stopwords removal

In [36]:
def remove_stopwords(text, lang='english'):
    # 1. Charger la liste des mots vides pour la langue choisie
    stop_words = set(stopwords.words(lang))
    
    # 2. Filtrer : on ne garde que les mots qui ne sont pas dans la liste
    # (en mettant tout en minuscule pour la comparaison)
    filtered_text = [w for w in text if w.lower() not in stop_words]
    
    return filtered_text

In [ ]:
text = [remove_stopwords(msg) for msg in tokenized]

In [38]:
print(text)

[['upgrdcentre', 'orange', 'customer', ',', 'may', 'claim', 'free', 'camera', 'phone', 'upgrade', 'loyalty', '.', 'call', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.', 'offer', 'ends', '<', 'masked', 'number', '>', 'th', 'july', '.', '&', 'c', "'s", 'apply', '.', 'opt-out', 'available'], ['loan', 'purpose', '£', '<', 'masked', 'number', '>', '-', '£', '<', 'masked', 'number', '>', ',', '<', 'masked', 'number', '>', '.', 'homeowners', '+', 'tenants', 'welcome', '.', 'previously', 'refused', '?', 'still', 'help', '.', 'call', 'free', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'text', 'back', "'help", "'"], ['contrast', '!', 'nokia', '<', 'masked', 'number', '>', 'video', 'camera', 'phone', 'call', '<', 'masked', 'number', '>', 'calls', 'cost', '<', 'masked', 'number', '>', 'ppm', 'ave', 'call', '<', 'masked', 'number', '>', 'mins', 'vary', 'mobiles', '<', 'masked', 'number', '>', '+', 'close', '<', 'masked', 'number', '>', 'post', 'bcm', '<', 'masked', 'number', '>', 'lon', 'wc', '<', 'masked', 'number', '>', 'n', '<', 'masked', 'number', '>', 'xx'], ['urgent', '!', 'mobile', 'number', 'awarded', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', 'land', 'line', '.', 'claim', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs'], ['someone', 'contacted', 'dating', 'service', 'entered', 'phone', 'fancy', '!', 'find', 'call', 'landing', '<', 'masked', 'number', '>', '.', 'box', '<', 'masked', 'number', '>', 'n', '<', 'masked', 'number', '>', 'tf', '<', 'masked', 'number', '>', 'p'], ['send', 'logo', '<', 'masked', 'number', '>', 'lover', '-', '<', 'masked', 'number', '>', 'names', 'joined', 'heart', '.', 'txt', 'love', 'name', '<', 'masked', 'number', '>', 'name', '<', 'masked', 'number', '>', 'mono', 'eg', 'love', 'adam', 'eve', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'yahoo', '!', 'box', '<', 'masked', 'number', '>', 'w', '<', 'masked', 'number', '>', 'wq', 'xeno', '<', 'masked', 'number', '>', 'ads', '<', 'masked', 'number', '>', 'p'], ['free', 'entry', '£', '<', 'masked', 'number', '>', 'weekly', 'competition', 'text', 'word', 'win', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '&', 'c', '<', 'weblink', '>'], ['<', 'masked', 'number', '>', 'dating', 'service', 'cal', ';', 'l', '<', 'masked', 'number', '>', 'box', '<', 'masked', 'number', '>', 'sk', '<', 'masked', 'number', '>', 'ch'], ['free', 'ringtone', 'text', 'first', '<', 'masked', 'number', '>', 'poly', 'text', 'get', '<', 'masked', 'number', '>', 'true', 'tone', '!', 'help', '?', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'st', 'free', ',', 'tones', '<', 'masked', 'number', '>', 'x£', '<', 'masked', 'number', '>', 'pw', 'e£nd', 'txt', 'stop'], ['<', 'masked', 'number', '>', 'myths', 'half', 'price', 'orange', 'line', 'rental', '&', 'latest', 'camera', 'phones', '<', 'masked', 'number', '>', 'free', '.', 'phone', '<', 'masked', 'number', '>', 'myths', '?', 'call', 'mobilesdirect', 'free', '<', 'masked', 'number', '>', 'update', '!', '<', 'masked', 'number', '>', 'stoptxt'], ['double', 'mins', 'texts', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'months', 'free', 'bluetooth', 'orange', '.', 'available', 'sony', ',', 'nokia', 'motorola', 'phones', '.', 'call', 'mobileupd', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'call', '<', 'masked', 'number', '>', 'output/n', '<', 'masked', 'number', '>', 'dx'], ['thanks', 'ringtone', 'order', ',', 'reference', '<', 'masked', 'number', '>', '.', 'charged', 'gb', '<', 'masked', 'number', '>', 'per', 'week', '.', 'subscribe', 'anytime', 'calling', 'customer', 'services', '<', 'masked', 'number', '>'], ['discount', 'code', 'rp', '<', 'masked', 'number', '>', '.', 'stop', 'messages', 'reply', 'stop', '.', '<', 'weblink', '>', 'customer', 'services', '<', 'masked', 'number', '>'], ['update_now', '-', 'mas', 'offer', '!', 'latest', 'motorola', ',', 'sonyericsson', '&', 'nokia', '&', 'free', 'bluetooth', '!', 'double', 'mins', '&', '<', 'masked', 'number', '>', 'txt', 'orange', '.', 'call', 'mobileupd', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'call', '<', 'masked', 'number', '>', 'output/f', '<', 'masked', 'number', '>', 'q='], ['cash-balance', 'currently', '<', 'masked', 'number', '>', 'pounds', '-', 'maximize', 'cash-in', 'send', 'cash', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'p/message', '.', 'cc', ':', '<', 'masked', 'number', '>', 'hg/suite', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', 'lands', 'row/w', '<', 'masked', 'number', '>', 'j', '<', 'masked', 'number', '>', 'hl'], ['congratulations', 'awarded', '<', 'masked', 'number', '>', 'cd', 'vouchers', '<', 'masked', 'number', '>', 'gift', 'guaranteed', '&', 'free', 'entry', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'draw', 'txt', 'music', '<', 'masked', 'number', '>', 'tns', '<', 'weblink', '>'], ['fancy', 'sha', '?', 'do.interested', '?', 'sextextuk.com', 'txt', 'uk', 'szy', '<', 'masked', 'number', '>', '.', 'texts', 'cost', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'per', 'message', '.', 'tns', 'website', '.', 'x'], ['valentines', 'day', 'special', '!', 'win', '£', '<', 'masked', 'number', '>', 'quiz', 'take', 'partner', 'trip', 'lifetime', '!', 'send', 'go', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'p/message', 'rcid', '.', 'custard', ':', '<', 'masked', 'number', '>', '.'], ['call', 'germany', '<', 'masked', 'number', '>', 'pence', 'per', 'minute', '!', 'call', 'fixed', 'line', 'via', 'access', 'number', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.', 'repayment', '.', 'direct', 'access', '!'], ['december', '!', 'mobile', '<', 'masked', 'number', '>', 'myths+', '?', 'entitled', 'update', 'latest', 'colour', 'camera', 'mobile', 'free', '!', 'call', 'mobile', 'update', 'co', 'free', '<', 'masked', 'number', '>'], ['think', 'smart', '?', 'win', '£', '<', 'masked', 'number', '>', 'week', 'weekly', 'quiz', ',', 'text', 'play', '<', 'masked', 'number', '>', '!', '&', 'cs', 'winnersclub', 'po', 'box', '<', 'masked', 'number', '>', ',', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'uz', '.', '<', 'masked', 'number', '>', '+', '.', 'gb', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '/week'], ['>', 'check', 'newest', 'selection', 'content', ',', 'games', ',', 'tones', ',', 'gossip', ',', 'bases', 'sport', ',', 'keep', 'mobile', 'fit', 'funky', 'text', 'wap', '<', 'masked', 'number', '>'], ['sms', '.', 'ac', 'blind', 'date', '<', 'masked', 'number', '>', 'u', '!', ':', 'roads', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '/m', 'aberdeen', ',', 'united', 'kingdom', '.', 'check', '<', 'weblink', '>', 'sms', '.', 'ac/w/icb', '<', 'masked', 'number', '>', 'city', '<', 'masked', 'number', '>', 'r', '<', 'masked', 'number', '>', '!', '-', '<', 'masked', 'number', '>', 'blind', 'dates', 'send', 'hide'], ['t-mobile', 'customer', 'may', 'claim', 'free', 'camera', 'phone', 'upgrade', '&', 'pay', '&', 'go', 'sim', 'card', 'loyalty', '.', 'call', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '.offer', 'ends', '<', 'masked', 'number', '>', 'the.t', '&', 'c', "'s", 'apply'], ['hmv', 'bonus', 'special', '<', 'masked', 'number', '>', 'pounds', 'genuine', 'hmv', 'vouchers', '.', 'answer', '<', 'masked', 'number', '>', 'easy', 'questions', '.', 'play', '!', 'send', 'hmv', '<', 'masked', 'number', '>', 'info', ':', '<', 'weblink', '>'], ['ringtone', 'club', ':', 'get', 'uk', 'singles', 'chart', 'mobile', 'week', 'choose', 'top', 'quality', 'ringtone', '!', 'message', 'free', 'charge', '.'], ['ringtone', 'service', 'changed', '!', '<', 'masked', 'number', '>', 'free', 'credits', '!', 'go', 'club', '<', 'masked', 'number', '>', 'mobiles.com', 'choose', 'content', '!', 'stop', '?', 'txt', 'club', 'stop', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'p/wk', 'club', '<', 'masked', 'number', '>', 'po', 'box', '<', 'masked', 'number', '>', 'mk', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'wt'], ['hey', 'really', 'horn', 'want', 'chat', 'see', 'naked', 'text', 'hot', '<', 'masked', 'number', '>', 'text', 'charged', '<', 'masked', 'number', '>', 'pm', 'subscribe', 'text', 'stop', '<', 'masked', 'number', '>'], ['tried', 'contact', 'reply', 'offer', 'video', 'handset', '?', '<', 'masked', 'number', '>', 'anytime', 'networks', 'mins', '?', 'unlimited', 'text', '?', 'camcorder', '?', 'reply', 'call', '<', 'masked', 'number', '>'], ['congratulations', 'awarded', '<', 'masked', 'number', '>', 'cd', 'vouchers', '<', 'masked', 'number', '>', 'gift', 'guaranteed', '&', 'free', 'entry', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'draw', 'txt', 'music', '<', 'masked', 'number', '>', 'tns', '<', 'weblink', '>'], ['<', 'masked', 'number', '>', 'secret', 'admirer', 'looking', '<', 'masked', 'number', '>', 'make', 'contact', 'you-find', 'r', '*', 'reveal', 'thinks', 'special-call', '<', 'masked', 'number', '>'], ['text', '&', 'meet', 'someone', 'sexy', 'today', '.', 'find', 'date', 'even', 'flirt', '.', 'join', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'p', '.', 'reply', 'name', '&', 'age', 'eg', 'sam', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '-message', 'red', '@', 'thirtyeight', 'pence'], ['meet', 'dream', 'partner', 'soon', '?', 'career', '<', 'masked', 'number', '>', 'flying', 'start', '?', '<', 'masked', 'number', '>', 'find', 'free', ',', 'txt', 'hero', 'followed', 'star', 'sign', ',', 'e.', 'g.', 'hero', 'tries'], ['<', 'masked', 'number', '>', 'new', 'mobiles', '<', 'masked', 'number', '>', ',', 'must', 'go', '!', 'txt', ':', 'nokia', ':', '<', 'masked', 'number', '>', '&', 'collect', 'today', '!', '£', '<', 'masked', 'number', '>', '<', 'weblink', '>', '<', 'masked', 'number', '>', 'output', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'gb/msg', '<', 'masked', 'number', '>'], ['unique', 'enough', '?', 'find', '<', 'masked', 'number', '>', 'th', 'august', '.', '<', 'weblink', '>'], ['please', 'call', 'customer', 'service', 'representative', 'freephone', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'am-', '<', 'masked', 'number', '>', 'pm', 'guaranteed', '£', '<', 'masked', 'number', '>', 'cash', '£', '<', 'masked', 'number', '>', 'prize', '!'], ['urgent', '!', 'trying', 'contact', '.', 'last', 'weekends', 'draw', 'shows', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', '.', 'claim', 'code', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs'], ['bangbabes', 'order', 'way', '.', 'receive', 'service', 'message', '<', 'masked', 'number', '>', 'download', 'content', '.', ',', 'goto', 'wap', '.', 'bang', '.', 'tv', 'mobile', 'internet/service', 'menu'], ['-pls', 'stop', 'bootydelious', '(', '<', 'masked', 'number', '>', '/f', ')', 'inviting', 'friend', '.', 'reply', 'yes-', '<', 'masked', 'number', '>', 'no-', '<', 'masked', 'number', '>', 'see', ':', '<', 'weblink', '>', 'stop', '?', 'send', 'stop', 'find', '<', 'masked', 'number', '>'], ['winner', 'specially', 'selected', '<', 'masked', 'number', '>', 'receive', '£', '<', 'masked', 'number', '>', 'cash', '<', 'masked', 'number', '>', '*', 'holiday', '(', 'flights', 'inc', ')', 'speak', 'live', 'operator', '<', 'masked', 'number', '>', 'claim', '<', 'masked', 'number', '>'], ['customer', 'service', 'announcement', '.', 'new', 'years', 'delivery', 'waiting', '.', 'please', 'call', '<', 'masked', 'number', '>', 'arrange', 'delivery'], ['frees', 'replied', 'text', '?', 'randy', ',', 'sexy', ',', 'female', 'live', 'local', '.', 'love', 'hear', '.', 'netcollex', 'ltd', '<', 'masked', 'number', '>', 'p', 'per', 'message', 'reply', 'stop', 'end'], ['rev', 'msg', 'chat', 'svc', '.', 'free', 'hardcore', 'services', 'text', 'go', ':', '<', 'masked', 'number', '>', 'get', 'nothing', 'must', 'age', 'verify', 'yr', 'network', '&', 'try'], ['want', '<', 'masked', 'number', '>', 'get', 'laid', 'tonight', '?', 'want', 'real', 'logging', 'locations', 'sent', 'direct', '<', 'masked', 'number', '>', 'mob', '?', 'join', 'uk', "'s", 'largest', 'logging', 'network', 'bt', 'texting', 'gravel', '<', 'masked', 'number', '>', '!', 'nt', '.', 'ec', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'p.message', '@', '<', 'masked', 'number', '>', 'p'], ['sunshine', 'quiz', 'q', '!', 'win', 'top', 'sony', 'dvd', 'player', 'know', 'country', 'algae', '?', 'txt', 'ans', '<', 'masked', 'number', '>', '.', '£', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'sp', ':', 'throne'], ['todays', 'vida', 'numbers', 'ending', '<', 'masked', 'number', '>', 'selected', 'receive', '$', '<', 'masked', 'number', '>', 'award', '.', 'match', 'please', 'call', '<', 'masked', 'number', '>', 'quoting', 'claim', 'code', '<', 'masked', 'number', '>', 'standard', 'rates', 'app'], ['urgent', '!', 'mobile', '.', 'awarded', '£', '<', 'masked', 'number', '>', 'bonus', 'caller', 'prize', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', '/', '<', 'masked', 'number', '>', 'final', 'try', 'contact', '!', 'call', 'landing', '<', 'masked', 'number', '>', 'box', '<', 'masked', 'number', '>', 'wr', '<', 'masked', 'number', '>', 'c', ',', '<', 'masked', 'number', '>', 'ppm'], ['private', '!', '<', 'masked', 'number', '>', 'account', 'statement', '<', 'masked', 'number', '>', 'shows', '<', 'masked', 'number', '>', 'redeemed', 'bonus', 'points', '.', 'claim', 'call', '<', 'masked', 'number', '>', 'identifier', 'code', ':', '<', 'masked', 'number', '>', 'expires'], ['winner', 'specially', 'selected', '<', 'masked', 'number', '>', 'receive', '£', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '*', 'holiday', '(', 'flights', 'inc', ')', 'speak', 'live', 'operator', '<', 'masked', 'number', '>', 'claim', '<', 'masked', 'number', '>', 'p/min', '(', '<', 'masked', 'number', '>', '+', ')'], ['gent', '!', 'trying', 'contact', '.', 'last', 'weekends', 'draw', 'shows', '£', '<', 'masked', 'number', '>', 'prize', 'guaranteed', '.', 'call', '<', 'masked', 'number', '>', '.', 'claim', 'code', 'k', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hrs', '.', '<', 'masked', 'number', '>', 'ppm'], ['please', 'call', 'customer', 'service', 'representative', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'am-', '<', 'masked', 'number', '>', 'pm', 'guaranteed', '£', '<', 'masked', 'number', '>', 'cash', '£', '<', 'masked', 'number', '>', 'prize', '!'], ['hear', 'new', '``', 'divorce', 'bare', "''", '?', 'comes', 'ken', "'s", 'stuff', '!'], ['urgent', 'awarded', 'complimentary', 'trip', 'eurodisinc', 'trap', ',', 'aco', '&', 'entry', '<', 'masked', 'number', '>', '£', '<', 'masked', 'number', '>', '.', 'claim', 'txt', 'dis', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', '+', '<', 'masked', 'number', '>', '*', '£', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', '(', 'morefrmmob', '.', 'shracomorsglsuplt', ')', '<', 'masked', 'number', '>', ',', 'ls', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'aj'], ['valued', 'customer', ',', 'pleased', 'advise', 'following', 'recent', 'review', 'mob', '.', 'awarded', '£', '<', 'masked', 'number', '>', 'bonus', 'prize', ',', 'call', '<', 'masked', 'number', '>'], ['contrast', '!', '<', 'masked', 'number', '>', 'year', 'special', 'cinema', 'pass', '<', 'masked', 'number', '>', '.', 'call', '<', 'masked', 'number', '>', '!', 'c', 'superman', 'v', ',', 'matrix', '<', 'masked', 'number', '>', ',', 'starwars', '<', 'masked', 'number', '>', ',', 'etc', '<', 'masked', 'number', '>', 'free', '!', 'bx', '<', 'masked', 'number', '>', '-ip', '<', 'masked', 'number', '>', '-', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'pm', '.', 'miss', '!'], ['sms', '.', 'ac', 'iptv', ':', 'new', 'jersey', 'devils', 'detroit', 'red', 'wings', 'play', 'ice', 'hockey', '.', 'correct', 'incorrect', '?', 'end', '?', 'reply', 'end', 'iptv'], ['<', 'masked', 'number', '>', '-', 'roger', 'burns', '-', 'message', '=', 'tried', 'call', 'reply', 'sms', 'free', 'nokia', 'mobile', '+', 'free', 'camcorder', '.', 'please', 'call', '<', 'masked', 'number', '>', 'delivery', 'tomorrow'], ['thanks', 'subscription', 'ringtone', 'uk', 'mobile', 'charged', '£', '<', 'masked', 'number', '>', '/month', 'please', 'confirm', 'replying', 'yes', '.', 'reply', 'charged'], ['england', 'v', 'macedonia', '-', 'miss', 'goals/team', 'news', '.', 'txt', 'national', 'team', '<', 'masked', 'number', '>', 'eg', 'england', '<', 'masked', 'number', '>', 'try', ':', 'wales', ',', 'scotland', '<', 'masked', 'number', '>', 'txt/ú', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'poboxox', '<', 'masked', 'number', '>', 'w', '<', 'masked', 'number', '>', 'wq', '<', 'masked', 'number', '>', '+'], ['xxxmobilemovieclub', ':', 'use', 'credit', ',', 'click', 'wap', 'link', 'next', 'txt', 'message', 'click', '>', '>', '<', 'weblink', '>', 'xxxmobilemovieclub.com', '?', 'n=qjkgighjjgcbl'], ['urgent', '!', '<', 'masked', 'number', '>', 'week', 'free', 'membership', '£', '<', 'masked', 'number', '>', ',', '<', 'masked', 'number', '>', 'prize', 'jackpot', '!', 'txt', 'word', ':', 'claim', ':', '<', 'masked', 'number', '>', '&', 'c', '<', 'weblink', '>', 'lccltd', 'box', '<', 'masked', 'number', '>', 'link', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', 'rw', '<', 'masked', 'number', '>'], ['six', 'chances', 'win', 'cash', '!', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', ',', '<', 'masked', 'number', '>', 'pounds', 'txt', '>', 'cs', '<', 'masked', 'number', '>', 'send', '<', 'masked', 'number', '>', '.', 'cost', '<', 'masked', 'number', '>', 'p/day', ',', '<', 'masked', 'number', '>', 'days', ',', '<', 'masked', 'number', '>', '+', 'stands', 'apply', 'reply', 'hl', '<', 'masked', 'number', '>', 'info'], ['mobile', '<', 'masked', 'number', '>', 'months', '?', 'r', 'entitled', 'update', 'latest', 'colour', 'mobiles', 'camera', 'free', '!', 'call', 'mobile', 'update', 'co', 'free', '<', 'masked', 'number', '>'], ['winner', '!', '!', 'valued', 'network', 'customer', 'selected', 'received', '£', '<', 'masked', 'number', '>', 'prize', 'reward', '!', 'claim', 'call', '<', 'masked', 'number', '>', '.', 'claim', 'code', 'kl', '<', 'masked', 'number', '>', '.', 'valid', '<', 'masked', 'number', '>', 'hours', '.'], ['frees', 'hey', 'darling', '<', 'masked', 'number', '>', 'week', "'s", 'word', 'back', '!', 'would', 'like', 'fun', 'still', '?', 'tb', 'ok', '!', 'xxx', 'std', 'chg', 'send', ',', '£', '<', 'masked', 'number', '>', '.', '<', 'masked', 'number', '>', 'rev'], ['free', 'entry', '<', 'masked', 'number', '>', 'comp', 'win', 'fa', 'cup', 'final', 'kts', '<', 'masked', 'number', '>', 'st', 'may', '<', 'masked', 'number', '>', '.', 'text', 'fa', '<', 'masked', 'number', '>', 'receive', 'entry', 'question', '(', 'std', 'txt', 'rate', ')', '&', 'c', "'s", 'apply', '<', 'masked', 'number', '>', '<', 'masked', 'number', '>', "'s"], ['de', 'asking', 'like', '.'], ['live', 'next', '&', 'lt', ';', '#', '&', 'gt', ';', 'mins'], ['running', 'managed', '<', 'masked', 'number', '>', 'minutes', 'needed', 'oxygen', '!', 'might', 'resort', 'roller', 'option', '!'], ['oh', '...', 'haha', '...', 'den', 'sold', 'went', 'today', '...', 'gee', ',', 'nevermind', 'la', '...', 'kai', ',', 'dun', 'mind', 'going', 'jazz', 'oso', '...', 'scared', 'hiphop', 'open', 'catch', '...'], ['need', '<', 'masked', 'numb

# Stemming

In [41]:
p = inflect.engine()
stemmer = PorterStemmer()

def stem_words(text):
    # Stemming : réduit chaque mot à sa racine (ex: scientific -> scientif)
    stems = [stemmer.stem(word) for word in text]

    return stems

stem_text = [stem_words(msg) for msg in text]

print(stem_text)

[['upgrdcentr', 'orang', 'custom', ',', 'may', 'claim', 'free', 'camera', 'phone', 'upgrad', 'loyalti', '.', 'call', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '.', 'offer', 'end', '<', 'mask', 'number', '>', 'th', 'juli', '.', '&', 'c', "'s", 'appli', '.', 'opt-out', 'avail'], ['loan', 'purpos', '£', '<', 'mask', 'number', '>', '-', '£', '<', 'mask', 'number', '>', ',', '<', 'mask', 'number', '>', '.', 'homeown', '+', 'tenant', 'welcom', '.', 'previous', 'refus', '?', 'still', 'help', '.', 'call', 'free', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'text', 'back', "'help", "'"], ['contrast', '!', 'nokia', '<', 'mask', 'number', '>', 'video', 'camera', 'phone', 'call', '<', 'mask', 'number', '>', 'call', 'cost', '<', 'mask', 'number', '>', 'ppm', 'ave', 'call', '<', 'mask', 'number', '>', 'min', 'vari', 'mobil', '<', 'mask', 'number', '>', '+', 'close', '<', 'mask', 'number', '>', 'post', 'bcm', '<', 'mask', 'number', '>', 'lon', 'wc', '<', 'mask', 'number', '>', 'n', '<', 'mask', 'number', '>', 'xx'], ['urgent', '!', 'mobil', 'number', 'award', '£', '<', 'mask', 'number', '>', 'prize', 'guarante', '.', 'call', '<', 'mask', 'number', '>', 'land', 'line', '.', 'claim', '<', 'mask', 'number', '>', '.', 'valid', '<', 'mask', 'number', '>', 'hr'], ['someon', 'contact', 'date', 'servic', 'enter', 'phone', 'fanci', '!', 'find', 'call', 'land', '<', 'mask', 'number', '>', '.', 'box', '<', 'mask', 'number', '>', 'n', '<', 'mask', 'number', '>', 'tf', '<', 'mask', 'number', '>', 'p'], ['send', 'logo', '<', 'mask', 'number', '>', 'lover', '-', '<', 'mask', 'number', '>', 'name', 'join', 'heart', '.', 'txt', 'love', 'name', '<', 'mask', 'number', '>', 'name', '<', 'mask', 'number', '>', 'mono', 'eg', 'love', 'adam', 'eve', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'yahoo', '!', 'box', '<', 'mask', 'number', '>', 'w', '<', 'mask', 'number', '>', 'wq', 'xeno', '<', 'mask', 'number', '>', 'ad', '<', 'mask', 'number', '>', 'p'], ['free', 'entri', '£', '<', 'mask', 'number', '>', 'weekli', 'competit', 'text', 'word', 'win', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', '&', 'c', '<', 'weblink', '>'], ['<', 'mask', 'number', '>', 'date', 'servic', 'cal', ';', 'l', '<', 'mask', 'number', '>', 'box', '<', 'mask', 'number', '>', 'sk', '<', 'mask', 'number', '>', 'ch'], ['free', 'rington', 'text', 'first', '<', 'mask', 'number', '>', 'poli', 'text', 'get', '<', 'mask', 'number', '>', 'true', 'tone', '!', 'help', '?', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'st', 'free', ',', 'tone', '<', 'mask', 'number', '>', 'x£', '<', 'mask', 'number', '>', 'pw', 'e£nd', 'txt', 'stop'], ['<', 'mask', 'number', '>', 'myth', 'half', 'price', 'orang', 'line', 'rental', '&', 'latest', 'camera', 'phone', '<', 'mask', 'number', '>', 'free', '.', 'phone', '<', 'mask', 'number', '>', 'myth', '?', 'call', 'mobilesdirect', 'free', '<', 'mask', 'number', '>', 'updat', '!', '<', 'mask', 'number', '>', 'stoptxt'], ['doubl', 'min', 'text', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'month', 'free', 'bluetooth', 'orang', '.', 'avail', 'soni', ',', 'nokia', 'motorola', 'phone', '.', 'call', 'mobileupd', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'call', '<', 'mask', 'number', '>', 'output/n', '<', 'mask', 'number', '>', 'dx'], ['thank', 'rington', 'order', ',', 'refer', '<', 'mask', 'number', '>', '.', 'charg', 'gb', '<', 'mask', 'number', '>', 'per', 'week', '.', 'subscrib', 'anytim', 'call', 'custom', 'servic', '<', 'mask', 'number', '>'], ['discount', 'code', 'rp', '<', 'mask', 'number', '>', '.', 'stop', 'messag', 'repli', 'stop', '.', '<', 'weblink', '>', 'custom', 'servic', '<', 'mask', 'number', '>'], ['update_now', '-', 'ma', 'offer', '!', 'latest', 'motorola', ',', 'sonyericsson', '&', 'nokia', '&', 'free', 'bluetooth', '!', 'doubl', 'min', '&', '<', 'mask', 'number', '>', 'txt', 'orang', '.', 'call', 'mobileupd', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'call', '<', 'mask', 'number', '>', 'output/f', '<', 'mask', 'number', '>', 'q='], ['cash-bal', 'current', '<', 'mask', 'number', '>', 'pound', '-', 'maxim', 'cash-in', 'send', 'cash', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'p/messag', '.', 'cc', ':', '<', 'mask', 'number', '>', 'hg/suit', '<', 'mask', 'number', '>', '/', '<', 'mask', 'number', '>', 'land', 'row/w', '<', 'mask', 'number', '>', 'j', '<', 'mask', 'number', '>', 'hl'], ['congratul', 'award', '<', 'mask', 'number', '>', 'cd', 'voucher', '<', 'mask', 'number', '>', 'gift', 'guarante', '&', 'free', 'entri', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'draw', 'txt', 'music', '<', 'mask', 'number', '>', 'tn', '<', 'weblink', '>'], ['fanci', 'sha', '?', 'do.interest', '?', 'sextextuk.com', 'txt', 'uk', 'szi', '<', 'mask', 'number', '>', '.', 'text', 'cost', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'per', 'messag', '.', 'tn', 'websit', '.', 'x'], ['valentin', 'day', 'special', '!', 'win', '£', '<', 'mask', 'number', '>', 'quiz', 'take', 'partner', 'trip', 'lifetim', '!', 'send', 'go', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'p/messag', 'rcid', '.', 'custard', ':', '<', 'mask', 'number', '>', '.'], ['call', 'germani', '<', 'mask', 'number', '>', 'penc', 'per', 'minut', '!', 'call', 'fix', 'line', 'via', 'access', 'number', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '.', 'repay', '.', 'direct', 'access', '!'], ['decemb', '!', 'mobil', '<', 'mask', 'number', '>', 'myths+', '?', 'entitl', 'updat', 'latest', 'colour', 'camera', 'mobil', 'free', '!', 'call', 'mobil', 'updat', 'co', 'free', '<', 'mask', 'number', '>'], ['think', 'smart', '?', 'win', '£', '<', 'mask', 'number', '>', 'week', 'weekli', 'quiz', ',', 'text', 'play', '<', 'mask', 'number', '>', '!', '&', 'cs', 'winnersclub', 'po', 'box', '<', 'mask', 'number', '>', ',', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'uz', '.', '<', 'mask', 'number', '>', '+', '.', 'gb', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', '/week'], ['>', 'check', 'newest', 'select', 'content', ',', 'game', ',', 'tone', ',', 'gossip', ',', 'base', 'sport', ',', 'keep', 'mobil', 'fit', 'funki', 'text', 'wap', '<', 'mask', 'number', '>'], ['sm', '.', 'ac', 'blind', 'date', '<', 'mask', 'number', '>', 'u', '!', ':', 'road', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '/m', 'aberdeen', ',', 'unit', 'kingdom', '.', 'check', '<', 'weblink', '>', 'sm', '.', 'ac/w/icb', '<', 'mask', 'number', '>', 'citi', '<', 'mask', 'number', '>', 'r', '<', 'mask', 'number', '>', '!', '-', '<', 'mask', 'number', '>', 'blind', 'date', 'send', 'hide'], ['t-mobil', 'custom', 'may', 'claim', 'free', 'camera', 'phone', 'upgrad', '&', 'pay', '&', 'go', 'sim', 'card', 'loyalti', '.', 'call', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '.offer', 'end', '<', 'mask', 'number', '>', 'the.t', '&', 'c', "'s", 'appli'], ['hmv', 'bonu', 'special', '<', 'mask', 'number', '>', 'pound', 'genuin', 'hmv', 'voucher', '.', 'answer', '<', 'mask', 'number', '>', 'easi', 'question', '.', 'play', '!', 'send', 'hmv', '<', 'mask', 'number', '>', 'info', ':', '<', 'weblink', '>'], ['rington', 'club', ':', 'get', 'uk', 'singl', 'chart', 'mobil', 'week', 'choos', 'top', 'qualiti', 'rington', '!', 'messag', 'free', 'charg', '.'], ['rington', 'servic', 'chang', '!', '<', 'mask', 'number', '>', 'free', 'credit', '!', 'go', 'club', '<', 'mask', 'number', '>', 'mobiles.com', 'choos', 'content', '!', 'stop', '?', 'txt', 'club', 'stop', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'p/wk', 'club', '<', 'mask', 'number', '>', 'po', 'box', '<', 'mask', 'number', '>', 'mk', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'wt'], ['hey', 'realli', 'horn', 'want', 'chat', 'see', 'nake', 'text', 'hot', '<', 'mask', 'number', '>', 'text', 'charg', '<', 'mask', 'number', '>', 'pm', 'subscrib', 'text', 'stop', '<', 'mask', 'number', '>'], ['tri', 'contact', 'repli', 'offer', 'video', 'handset', '?', '<', 'mask', 'number', '>', 'anytim', 'network', 'min', '?', 'unlimit', 'text', '?', 'camcord', '?', 'repli', 'call', '<', 'mask', 'number', '>'], ['congratul', 'award', '<', 'mask', 'number', '>', 'cd', 'voucher', '<', 'mask', 'number', '>', 'gift', 'guarante', '&', 'free', 'entri', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'draw', 'txt', 'music', '<', 'mask', 'number', '>', 'tn', '<', 'weblink', '>'], ['<', 'mask', 'number', '>', 'secret', 'admir', 'look', '<', 'mask', 'number', '>', 'make', 'contact', 'you-find', 'r', '*', 'reveal', 'think', 'special-cal', '<', 'mask', 'number', '>'], ['text', '&', 'meet', 'someon', 'sexi', 'today', '.', 'find', 'date', 'even', 'flirt', '.', 'join', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'p', '.', 'repli', 'name', '&', 'age', 'eg', 'sam', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', '-messag', 'red', '@', 'thirtyeight', 'penc'], ['meet', 'dream', 'partner', 'soon', '?', 'career', '<', 'mask', 'number', '>', 'fli', 'start', '?', '<', 'mask', 'number', '>', 'find', 'free', ',', 'txt', 'hero', 'follow', 'star', 'sign', ',', 'e.', 'g.', 'hero', 'tri'], ['<', 'mask', 'number', '>', 'new', 'mobil', '<', 'mask', 'number', '>', ',', 'must', 'go', '!', 'txt', ':', 'nokia', ':', '<', 'mask', 'number', '>', '&', 'collect', 'today', '!', '£', '<', 'mask', 'number', '>', '<', 'weblink', '>', '<', 'mask', 'number', '>', 'output', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'gb/msg', '<', 'mask', 'number', '>'], ['uniqu', 'enough', '?', 'find', '<', 'mask', 'number', '>', 'th', 'august', '.', '<', 'weblink', '>'], ['pleas', 'call', 'custom', 'servic', 'repres', 'freephon', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'am-', '<', 'mask', 'number', '>', 'pm', 'guarante', '£', '<', 'mask', 'number', '>', 'cash', '£', '<', 'mask', 'number', '>', 'prize', '!'], ['urgent', '!', 'tri', 'contact', '.', 'last', 'weekend', 'draw', 'show', '£', '<', 'mask', 'number', '>', 'prize', 'guarante', '.', 'call', '<', 'mask', 'number', '>', '.', 'claim', 'code', '<', 'mask', 'number', '>', '.', 'valid', '<', 'mask', 'number', '>', 'hr'], ['bangbab', 'order', 'way', '.', 'receiv', 'servic', 'messag', '<', 'mask', 'number', '>', 'download', 'content', '.', ',', 'goto', 'wap', '.', 'bang', '.', 'tv', 'mobil', 'internet/servic', 'menu'], ['-pl', 'stop', 'bootydeli', '(', '<', 'mask', 'number', '>', '/f', ')', 'invit', 'friend', '.', 'repli', 'yes-', '<', 'mask', 'number', '>', 'no-', '<', 'mask', 'number', '>', 'see', ':', '<', 'weblink', '>', 'stop', '?', 'send', 'stop', 'find', '<', 'mask', 'number', '>'], ['winner', 'special', 'select', '<', 'mask', 'number', '>', 'receiv', '£', '<', 'mask', 'number', '>', 'cash', '<', 'mask', 'number', '>', '*', 'holiday', '(', 'flight', 'inc', ')', 'speak', 'live', 'oper', '<', 'mask', 'number', '>', 'claim', '<', 'mask', 'number', '>'], ['custom', 'servic', 'announc', '.', 'new', 'year', 'deliveri', 'wait', '.', 'pleas', 'call', '<', 'mask', 'number', '>', 'arrang', 'deliveri'], ['free', 'repli', 'text', '?', 'randi', ',', 'sexi', ',', 'femal', 'live', 'local', '.', 'love', 'hear', '.', 'netcollex', 'ltd', '<', 'mask', 'number', '>', 'p', 'per', 'messag', 'repli', 'stop', 'end'], ['rev', 'msg', 'chat', 'svc', '.', 'free', 'hardcor', 'servic', 'text', 'go', ':', '<', 'mask', 'number', '>', 'get', 'noth', 'must', 'age', 'verifi', 'yr', 'network', '&', 'tri'], ['want', '<', 'mask', 'number', '>', 'get', 'laid', 'tonight', '?', 'want', 'real', 'log', 'locat', 'sent', 'direct', '<', 'mask', 'number', '>', 'mob', '?', 'join', 'uk', "'s", 'largest', 'log', 'network', 'bt', 'text', 'gravel', '<', 'mask', 'number', '>', '!', 'nt', '.', 'ec', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'p.messag', '@', '<', 'mask', 'number', '>', 'p'], ['sunshin', 'quiz', 'q', '!', 'win', 'top', 'soni', 'dvd', 'player', 'know', 'countri', 'alga', '?', 'txt', 'an', '<', 'mask', 'number', '>', '.', '£', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'sp', ':', 'throne'], ['today', 'vida', 'number', 'end', '<', 'mask', 'number', '>', 'select', 'receiv', '$', '<', 'mask', 'number', '>', 'award', '.', 'match', 'pleas', 'call', '<', 'mask', 'number', '>', 'quot', 'claim', 'code', '<', 'mask', 'number', '>', 'standard', 'rate', 'app'], ['urgent', '!', 'mobil', '.', 'award', '£', '<', 'mask', 'number', '>', 'bonu', 'caller', 'prize', '<', 'mask', 'number', '>', '/', '<', 'mask', 'number', '>', '/', '<', 'mask', 'number', '>', 'final', 'tri', 'contact', '!', 'call', 'land', '<', 'mask', 'number', '>', 'box', '<', 'mask', 'number', '>', 'wr', '<', 'mask', 'number', '>', 'c', ',', '<', 'mask', 'number', '>', 'ppm'], ['privat', '!', '<', 'mask', 'number', '>', 'account', 'statement', '<', 'mask', 'number', '>', 'show', '<', 'mask', 'number', '>', 'redeem', 'bonu', 'point', '.', 'claim', 'call', '<', 'mask', 'number', '>', 'identifi', 'code', ':', '<', 'mask', 'number', '>', 'expir'], ['winner', 'special', 'select', '<', 'mask', 'number', '>', 'receiv', '£', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '*', 'holiday', '(', 'flight', 'inc', ')', 'speak', 'live', 'oper', '<', 'mask', 'number', '>', 'claim', '<', 'mask', 'number', '>', 'p/min', '(', '<', 'mask', 'number', '>', '+', ')'], ['gent', '!', 'tri', 'contact', '.', 'last', 'weekend', 'draw', 'show', '£', '<', 'mask', 'number', '>', 'prize', 'guarante', '.', 'call', '<', 'mask', 'number', '>', '.', 'claim', 'code', 'k', '<', 'mask', 'number', '>', '.', 'valid', '<', 'mask', 'number', '>', 'hr', '.', '<', 'mask', 'number', '>', 'ppm'], ['pleas', 'call', 'custom', 'servic', 'repres', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'am-', '<', 'mask', 'number', '>', 'pm', 'guarante', '£', '<', 'mask', 'number', '>', 'cash', '£', '<', 'mask', 'number', '>', 'prize', '!'], ['hear', 'new', '``', 'divorc', 'bare', "''", '?', 'come', 'ken', "'s", 'stuff', '!'], ['urgent', 'award', 'complimentari', 'trip', 'eurodisinc', 'trap', ',', 'aco', '&', 'entri', '<', 'mask', 'number', '>', '£', '<', 'mask', 'number', '>', '.', 'claim', 'txt', 'di', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', '+', '<', 'mask', 'number', '>', '*', '£', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', '(', 'morefrmmob', '.', 'shracomorsglsuplt', ')', '<', 'mask', 'number', '>', ',', 'ls', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'aj'], ['valu', 'custom', ',', 'pleas', 'advis', 'follow', 'recent', 'review', 'mob', '.', 'award', '£', '<', 'mask', 'number', '>', 'bonu', 'prize', ',', 'call', '<', 'mask', 'number', '>'], ['contrast', '!', '<', 'mask', 'number', '>', 'year', 'special', 'cinema', 'pass', '<', 'mask', 'number', '>', '.', 'call', '<', 'mask', 'number', '>', '!', 'c', 'superman', 'v', ',', 'matrix', '<', 'mask', 'number', '>', ',', 'starwar', '<', 'mask', 'number', '>', ',', 'etc', '<', 'mask', 'number', '>', 'free', '!', 'bx', '<', 'mask', 'number', '>', '-ip', '<', 'mask', 'number', '>', '-', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'pm', '.', 'miss', '!'], ['sm', '.', 'ac', 'iptv', ':', 'new', 'jersey', 'devil', 'detroit', 'red', 'wing', 'play', 'ice', 'hockey', '.', 'correct', 'incorrect', '?', 'end', '?', 'repli', 'end', 'iptv'], ['<', 'mask', 'number', '>', '-', 'roger', 'burn', '-', 'messag', '=', 'tri', 'call', 'repli', 'sm', 'free', 'nokia', 'mobil', '+', 'free', 'camcord', '.', 'pleas', 'call', '<', 'mask', 'number', '>', 'deliveri', 'tomorrow'], ['thank', 'subscript', 'rington', 'uk', 'mobil', 'charg', '£', '<', 'mask', 'number', '>', '/month', 'pleas', 'confirm', 'repli', 'ye', '.', 'repli', 'charg'], ['england', 'v', 'macedonia', '-', 'miss', 'goals/team', 'news', '.', 'txt', 'nation', 'team', '<', 'mask', 'number', '>', 'eg', 'england', '<', 'mask', 'number', '>', 'tri', ':', 'wale', ',', 'scotland', '<', 'mask', 'number', '>', 'txt/ú', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'poboxox', '<', 'mask', 'number', '>', 'w', '<', 'mask', 'number', '>', 'wq', '<', 'mask', 'number', '>', '+'], ['xxxmobilemovieclub', ':', 'use', 'credit', ',', 'click', 'wap', 'link', 'next', 'txt', 'messag', 'click', '>', '>', '<', 'weblink', '>', 'xxxmobilemovieclub.com', '?', 'n=qjkgighjjgcbl'], ['urgent', '!', '<', 'mask', 'number', '>', 'week', 'free', 'membership', '£', '<', 'mask', 'number', '>', ',', '<', 'mask', 'number', '>', 'prize', 'jackpot', '!', 'txt', 'word', ':', 'claim', ':', '<', 'mask', 'number', '>', '&', 'c', '<', 'weblink', '>', 'lccltd', 'box', '<', 'mask', 'number', '>', 'link', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', 'rw', '<', 'mask', 'number', '>'], ['six', 'chanc', 'win', 'cash', '!', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', ',', '<', 'mask', 'number', '>', 'pound', 'txt', '>', 'cs', '<', 'mask', 'number', '>', 'send', '<', 'mask', 'number', '>', '.', 'cost', '<', 'mask', 'number', '>', 'p/day', ',', '<', 'mask', 'number', '>', 'day', ',', '<', 'mask', 'number', '>', '+', 'stand', 'appli', 'repli', 'hl', '<', 'mask', 'number', '>', 'info'], ['mobil', '<', 'mask', 'number', '>', 'month', '?', 'r', 'entitl', 'updat', 'latest', 'colour', 'mobil', 'camera', 'free', '!', 'call', 'mobil', 'updat', 'co', 'free', '<', 'mask', 'number', '>'], ['winner', '!', '!', 'valu', 'network', 'custom', 'select', 'receiv', '£', '<', 'mask', 'number', '>', 'prize', 'reward', '!', 'claim', 'call', '<', 'mask', 'number', '>', '.', 'claim', 'code', 'kl', '<', 'mask', 'number', '>', '.', 'valid', '<', 'mask', 'number', '>', 'hour', '.'], ['free', 'hey', 'darl', '<', 'mask', 'number', '>', 'week', "'s", 'word', 'back', '!', 'would', 'like', 'fun', 'still', '?', 'tb', 'ok', '!', 'xxx', 'std', 'chg', 'send', ',', '£', '<', 'mask', 'number', '>', '.', '<', 'mask', 'number', '>', 'rev'], ['free', 'entri', '<', 'mask', 'number', '>', 'comp', 'win', 'fa', 'cup', 'final', 'kt', '<', 'mask', 'number', '>', 'st', 'may', '<', 'mask', 'number', '>', '.', 'text', 'fa', '<', 'mask', 'number', '>', 'receiv', 'entri', 'question', '(', 'std', 'txt', 'rate', ')', '&', 'c', "'s", 'appli', '<', 'mask', 'number', '>', '<', 'mask', 'number', '>', "'s"], ['de', 'ask', 'like', '.'], ['live', 'next', '&', 'lt', ';', '#', '&', 'gt', ';', 'min'], ['run', 'manag', '<', 'mask', 'number', '>', 'minut', 'need', 'oxygen', '!', 'might', 'resort', 'roller', 'option', '!'], ['oh', '...', 'haha', '...', 'den', 'sold', 'went', 'today', '...', 'gee', ',', 'nevermind', 'la', '...', 'kai', ',', 'dun', 'mind', 'go', 'jazz', 'oso', '...', 'scare', 'hiphop', 'open', 'catch', '...'], ['need', '<', 'mask', 'number', '>', 'th', 'campu', 'atm', ',', 'could', 'pick', 'hour', 'two', '?'], ['<', 'mask', 'number', '>', 'put', 'da', 'font', '!', '!'], ['plan', 'stay', 'night', 'probabl', 'back', 'til', 'late'], ['hey', 'j', '!', 'r', 'feel', 'better', ',', 'hope', 'funni', '.', 'feel', 'ill', '&', 'think', 'may', 'tonsolitusaswel', '!', 'damn', 'iam', 'latin', 'feder', 'bore', '.', 'lot', 'love', 'xxxx'], ['free', ':', 'txt', ':', 'call', ':', '<', 'mask', 'number', '>', '&', 'claim', 'reward', '<', 'mask', 'number', '>', 'hour', 'talk', 'time', 'use', 'phone', '!', 'subscrib', '<', 'mask', 'number', '>', 'gb/math', 'inc', '<', 'mask', 'number', '>', 'hr', '<', 'mask', 'number', '>', 'stop', '?', 'txtstop'], ['hi', 'decid', 'wot', '<', 'mask', 'number', '>', 'get', '<', 'mask', 'number', '>', 'birthday', 'ill', 'pro', 'ju', 'get', 'voucher', 'frm', 'virgin', 'surf'], ['laid', 'airtel', 'line', 'rest', '?'], ['stuck', 'da', 'middl', 'da', 'row', 'da', 'right', 'hand', 'side', 'da', 'lt', '...'], ['full', 'heat', 'pa', ':', '-', ')', 'appli', 'oil', 'pa', '.'], ['c

# Lemmatization

In [44]:
nlp = spacy.load("en_core_web_sm")

def lemmatize_text(text):
    text = " ".join(text)
    doc = nlp(text)
    # On récupère le lemme de chaque token
    return ' '.join([token.lemma_ for token in doc])


lema_text = [lemmatize_text(msg) for msg in text]

In [45]:
print(lema_text)

["upgrdcentre orange customer , may claim free camera phone upgrade loyalty . call < mask number > < mask number > < mask number > . offer end < mask number > th july . & c 's apply . opt - out available", "loan purpose £ < mask number > - £ < mask number > , < mask number > . homeowner + tenant welcome . previously refuse ? still help . call free < mask number > < mask number > text back ' help '", 'contrast ! nokia < mask number > video camera phone call < mask number > call cost < mask number > ppm ave call < mask number > min vary mobile < mask number > + close < mask number > post bcm < mask number > lon wc < mask number > n < mask number > xx', 'urgent ! mobile number award £ < mask number > prize guarantee . call < mask number > land line . claim < mask number > . valid < mask number > hrs', 'someone contact date service enter phone fancy ! find call landing < mask number > . box < mask number > n < mask number > tf < mask number > p', 'send logo < mask number > lover - < mask number > name join heart . txt love name < mask number > name < mask number > mono eg love adam eve < mask number > < mask number > yahoo ! box < mask number > w < mask number > wq xeno < mask number > ad < mask number > p', 'free entry £ < mask number > weekly competition text word win < mask number > . < mask number > & c < weblink >', '< mask number > date service cal ; l < mask number > box < mask number > sk < mask number > ch', 'free ringtone text first < mask number > poly text get < mask number > true tone ! help ? < mask number > < mask number > < mask number > < mask number > st free , tone < mask number > x£ < mask number > pw e£nd txt stop', '< mask number > myth half price orange line rental & late camera phone < mask number > free . phone < mask number > myth ? call mobilesdirect free < mask number > update ! < mask number > stoptxt', 'double min text < mask number > < mask number > month free bluetooth orange . available sony , nokia motorola phone . call mobileupd < mask number > < mask number > call < mask number > output / n < mask number > dx', 'thank ringtone order , reference < mask number > . charge gb < mask number > per week . subscribe anytime call customer service < mask number >', 'discount code rp < mask number > . stop message reply stop . < weblink > customer service < mask number >', 'update_now - mas offer ! late motorola , sonyericsson & nokia & free bluetooth ! double min & < mask number > txt orange . call mobileupd < mask number > < mask number > call < mask number > output / f < mask number > q=', 'cash - balance currently < mask number > pound - maximize cash - in send cash < mask number > < mask number > p / message . cc : < mask number > hg / suite < mask number > / < mask number > land row / w < mask number > j < mask number > hl', 'congratulation award < mask number > cd voucher < mask number > gift guarantee & free entry < mask number > < mask number > draw txt music < mask number > tns < weblink >', 'fancy sha ? do.intereste ? sextextuk.com txt uk szy < mask number > . text cost < mask number > . < mask number > per message . tns website . x', 'valentine day special ! win £ < mask number > quiz take partner trip lifetime ! send go < mask number > . < mask number > p / message rcid . custard : < mask number > .', 'call germany < mask number > penny per minute ! call fix line via access number < mask number > < mask number > < mask number > < mask number > . repayment . direct access !', 'december ! mobile < mask number > myths+ ? entitle update late colour camera mobile free ! call mobile update co free < mask number >', 'think smart ? win £ < mask number > week weekly quiz , text play < mask number > ! & cs winnersclub po box < mask number > , < mask number > < mask number > uz . < mask number > + . gb < mask number > . < mask number > /week', '> check new selection content , game , tone , gossip , base sport , keep mobile fit funky text wap < mask number >', 'sms . ac blind date < mask number > u ! : road < mask number > < mask number > /m aberdeen , united kingdom . check < weblink > sms . ac / w / icb < mask number > city < mask number > r < mask number > ! - < mask number > blind date send hide', "t - mobile customer may claim free camera phone upgrade & pay & go sim card loyalty . call < mask number > < mask number > < mask number > .offer end < mask number > the.t & c 's apply", 'hmv bonus special < mask number > pound genuine hmv voucher . answer < mask number > easy question . play ! send hmv < mask number > info : < weblink >', 'ringtone club : get uk single chart mobile week choose top quality ringtone ! message free charge .', 'ringtone service change ! < mask number > free credit ! go club < mask number > mobiles.com choose content ! stop ? txt club stop < mask number > . < mask number > p / wk club < mask number > po box < mask number > mk < mask number > < mask number > wt', 'hey really horn want chat see naked text hot < mask number > text charge < mask number > pm subscribe text stop < mask number >', 'try contact reply offer video handset ? < mask number > anytime network min ? unlimited text ? camcorder ? reply call < mask number >', 'congratulation award < mask number > cd voucher < mask number > gift guarantee & free entry < mask number > < mask number > draw txt music < mask number > tns < weblink >', '< mask number > secret admirer look < mask number > make contact you - find r * reveal think special - call < mask number >', 'text & meet someone sexy today . find date even flirt . join < mask number > < mask number > p . reply name & age eg sam < mask number > . < mask number > -message red @ thirtyeight pence', 'meet dream partner soon ? career < mask number > fly start ? < mask number > find free , txt hero follow star sign , e. g. hero try', '< mask number > new mobile < mask number > , must go ! txt : nokia : < mask number > & collect today ! £ < mask number > < weblink > < mask number > output < mask number > . < mask number > gb / msg < mask number >', 'unique enough ? find < mask number > th august . < weblink >', 'please call customer service representative freephone < mask number > < mask number > < mask number > < mask number > am- < mask number > pm guarantee £ < mask number > cash £ < mask number > prize !', 'urgent ! try contact . last weekend draw show £ < mask number > prize guarantee . call < mask number > . claim code < mask number > . valid < mask number > hrs', 'bangbabe order way . receive service message < mask number > download content . , goto wap . bang . tv mobile internet / service menu', '-pls stop bootydelious ( < mask number > /f ) invite friend . reply yes- < mask number > no- < mask number > see : < weblink > stop ? send stop find < mask number >', 'winner specially select < mask number > receive £ < mask number > cash < mask number > * holiday ( flight inc ) speak live operator < mask number > claim < mask number >', 'customer service announcement . new year delivery wait . please call < mask number > arrange delivery', 'free reply text ? randy , sexy , female live local . love hear . netcollex ltd < mask number > p per message reply stop end', 'rev msg chat svc . free hardcore service text go : < mask number > get nothing must age verify yr network & try', "want < mask number > get lay tonight ? want real logging location send direct < mask number > mob ? join uk 's large log network bt texting gravel < mask number > ! not . ec < mask number > . < mask number > p.message @ < mask number > p", 'sunshine quiz q ! win top sony dvd player know country algae ? txt an < mask number > . £ < mask number > . < mask number > sp : throne', 'todays vida number end < mask number > select receive $ < mask number > award . match please call < mask number > quote claim code < mask number > standard rate app', 'urgent ! mobile . award £ < mask number > bonus caller prize < mask number > / < mask number > / < mask number > final try contact ! call landing < mask number > box < mask number > wr < mask number > c , < mask number > ppm', 'private ! < mask number > account statement < mask number > show < mask number > redeem bonus point . claim call < mask number > identifier code : < mask number > expire', 'winner specially select < mask number > receive £ < mask number > < mask number > * holiday ( flight inc ) speak live operator < mask number > claim < mask number > p / min ( < mask number > + )', 'gent ! try contact . last weekend draw show £ < mask number > prize guarantee . call < mask number > . claim code k < mask number > . valid < mask number > hrs . < mask number > ppm', 'please call customer service representative < mask number > < mask number > < mask number > < mask number > am- < mask number > pm guarantee £ < mask number > cash £ < mask number > prize !', "hear new ` ` divorce bare '' ? come ken 's stuff !", 'urgent award complimentary trip eurodisinc trap , aco & entry < mask number > £ < mask number > . claim txt dis < mask number > < mask number > + < mask number > * £ < mask number > . < mask number > ( morefrmmob . shracomorsglsuplt ) < mask number > , ls < mask number > < mask number > aj', 'value customer , please advise follow recent review mob . award £ < mask number > bonus prize , call < mask number >', 'contrast ! < mask number > year special cinema pass < mask number > . call < mask number > ! c superman v , matrix < mask number > , starwar < mask number > , etc < mask number > free ! bx < mask number > -ip < mask number > - < mask number > . < mask number > pm . miss !', 'sms . ac iptv : new jersey devil detroit red wing play ice hockey . correct incorrect ? end ? reply end iptv', '< mask number > - roger burns - message = try call reply sm free nokia mobile + free camcorder . please call < mask number > delivery tomorrow', 'thanks subscription ringtone uk mobile charge £ < mask number > /month please confirm reply yes . reply charge', 'england v macedonia - miss goal / team news . txt national team < mask number > eg england < mask number > try : wale , scotland < mask number > txt / ú < mask number > . < mask number > poboxox < mask number > w < mask number > wq < mask number > +', 'xxxmobilemovieclub : use credit , click wap link next txt message click > > < weblink > xxxmobilemovieclub.com ? n = qjkgighjjgcbl', 'urgent ! < mask number > week free membership £ < mask number > , < mask number > prize jackpot ! txt word : claim : < mask number > & c < weblink > lccltd box < mask number > link < mask number > < mask number > rw < mask number >', 'six chance win cash ! < mask number > < mask number > , < mask number > pound txt > cs < mask number > send < mask number > . cost < mask number > p / day , < mask number > day , < mask number > + stand apply reply hl < mask number > info', 'mobile < mask number > month ? r entitle update late colour mobile camera free ! call mobile update co free < mask number >', 'winner ! ! value network customer select receive £ < mask number > prize reward ! claim call < mask number > . claim code kl < mask number > . valid < mask number > hour .', "free hey darling < mask number > week 's word back ! would like fun still ? tb ok ! xxx std chg send , £ < mask number > . < mask number > rev", "free entry < mask number > comp win fa cup final kts < mask number > st may < mask number > . text fa < mask number > receive entry question ( std txt rate ) & c 's apply < mask number > < mask number > be", 'de ask like .', 'live next & lt ; # & gt ; min', 'run manage < mask number > minute need oxygen ! might resort roller option !', 'oh ... haha ... den sell go today ... gee , nevermind la ... kai , dun mind go jazz oso ... scar hiphop open catch ...', 'need < mask number > th campus atm , could pick hour two ?', '< mask number > put da font ! !', 'plan staying night probably back til late', 'hey j ! r feel well , hop funny . feel ill & think may tonsolitusaswell ! damn iam latin federal bored . lot love xxxx', 'free : txt : call : < mask number > & claim reward < mask number > hour talk time use phone ! subscribe < mask number > gb / math inc < mask number > hrs < mask number > stop ? txtstop', 'hi decide wot < mask number > get < mask number > birthday ill pro jus get voucher frm virgin surf', 'lay airtel line rest ?', 'stick da middle da row da right hand side da lt ...', 'full heat pa : - ) apply oil pa .', 'carlos pick , swing usf little bit', 'yo sorry shower sup', 'good time . nice something bit different weekend change . see ya soon', 'ok b angry . message aft come home tonight .', 'right phone someone number like !', 'well do england ! get official poly ringtone colour flag yer mobile ! text tone flag < mask number > ! opt - out txt eng stop . box < mask number > w < mask number > wx £ < mask number > . < mask number >', 'tomorrow go theatre . . . come wherever call . . . tell come tomorrow', 'finish work yet something ?', 'want wish happy new year want talk legal advice gary split person . make trip tbo . hope everything good babe love ya : )', 'see swing bit , get thing take care first', 'mile , age < mask number > , blonde , new uk . look sex uk guy . like fun . text talk < mask number > . < mask number > . < mask number > pp / txt < mask number > st < mask number > free . £ < mask number > . < mask number > increment . help < mask number >', 'secret admirer look < mask number > make contact you - find r * reveal think special - call < mask number > -stops- < mask number > ppm', 'noooooooo please . last thing need stress . life fair .', "chance win £ < mask number > shopping spree txt : shop < mask number > . 's & c 's < weblink > custard < mask number > , < mask number > x < mask number > p / wk", 'wow think common . take back freak ! unless chop : - )', 'course . math one day one chapter one month finish .', 'hi .... engagement find & lt ; # & gt ; th next month . know really shock bt .... hmm njan vilikkam .... ws al sun ; - ( .', 'plan yet . ?', 'urgent ! call < mask number > landing . complimentary < mask number > * biz holiday < mask number > , < mask number > cash await collection sae & cs po box < mask number > sk < mask number > < mask number > wp < mask number > ppm < mask number > +', 'contract mobile < mask number > month ? late motorola , nokia etc . free ! double min & text orange tariff . text yes rollback , remove record', 'congratulation award < mask number > cd voucher < mask number > gift guarantee & free entry < mask number > < mask number > draw txt music < mask number >', 'directly behind ... < mask number > row behind ü ...', ': ( ....', 'urgent ! < mask number > nd attempt contact ! £ < mask number > call < mask number > < mask number > & cbc < mask number > wc < mask number > n < mask number > xx.callcost < mask number > ppmmobilesvary . max£ < mask number > . < mask number >', 'omg know eat ?', 'cha quiteamuze that\x92school babe , propos & cu cathen funny < mask number > brekkie ! love jen xxx . extra lrg portion < mask number > please', 'want laugh ? try chit - chat mobile ! logo texte word : chat send : < mask number > cm po box < mask number > london w < mask number > < mask number > zf < mask number > + < mask number > p / message rcid', 'time come tomorrow', 'miya go sunny africa ? hope r akin good time . give big old silver back big kiss .', 'together think', 'buy blackberry bold < mask number > torch . buy new use . let know . plus say buy & lt ; # & gt ; g wifi ipad . say & lt ; # & gt ; g ?', 'honeydew say : * sweet world * god laugh & amp ; say : * wait , hant meet person read message * moral : even god crack joke ! gm+gn+ge+gn : )', 'tell address', 'come around & lt ; decimal & gt ; pm vkey .. outside nw , il come time', 'much try get ?', 'good afternoon bottom . go walk day ? get police abstract ? still ? wake miss babe', 'awake oh . .', 'think + da . wil .', 'piss talk someone realise point . ( read backwards )', 'hospital da . . return home evening', 'get rd ship comp', "< mask number > wonder world < mask number > th < mask number > th style < mask number > th smile < mask number > th personality < mask number > rd nature < mask number > nd sms < mask number > st ` ` lovely friendship '' ... good morning dear", 'try something dear . read something exam', 'sun ah ... may dun anything ... book e lesson ... e plates orchard mrt noe hor ...', 'symptom love : ` ` < mask number > .you like listen song < mask number > .you get stop see name belove < mask number > .you get angry', 'great . safe trip . panic surrender .']

# exercise 3

In [46]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))
nlp = spacy.load("en_core_web_sm")

# --- FONCTIONS DE PRÉPARATION ---

def remove_noise(text):
    # Supprime ponctuation et caractères spéciaux
    text = re.sub(r'[^\w\s]', '', text)
    # Supprime les balises spécifiques si présentes (ex: <mask number>)
    text = text.replace('mask number', '').replace('weblink', '')
    return text

def lemmatize_list(word_list):
    # On transforme la liste en string pour spaCy
    doc = nlp(" ".join(word_list))
    return [token.lemma_ for token in doc]

# --- CRÉATION DES 9 COLONNES ---

# 1. & 2. Colonnes existantes (S.No, Message_body, Label)

# 3. Case Normalization
df['Case Normalization'] = df['Message_body'].str.lower()

# 4. Noise Removal
df['Noise Removal'] = df['Case Normalization'].apply(remove_noise)

# 5. Tokenization
df['Tokenization'] = df['Noise Removal'].apply(word_tokenize)

# 6. Stopwords Removal
df['Stopwords'] = df['Tokenization'].apply(
    lambda x: [word for word in x if word not in stop_words and word.isalnum()]
)

# 7. Stemming (sur la colonne Stopwords)
df['Stemming'] = df['Stopwords'].apply(
    lambda x: [stemmer.stem(word) for word in x]
)

# 8. Lemmatization (sur la colonne Stopwords - important de ne pas le faire sur le stemming)
df['Lemmatization'] = df['Stopwords'].apply(lemmatize_list)

# Affichage du résultat final (les 9 colonnes)
print(f"Nombre de colonnes : {len(df.columns)}")
df.head()

Nombre de colonnes : 9

,S. No.,Message_body,Label,Case Normalization,Noise Removal,Tokenization,Stopwords,Stemming,Lemmatization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,...","[upgrdcentre, orange, customer, may, claim, fr...","[upgrdcentr, orang, custom, may, claim, free, ...","[upgrdcentre, orange, customer, may, claim, fr..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose 500 75000 homeowners te...,"[loan, for, any, purpose, 500, 75000, homeowne...","[loan, purpose, 500, 75000, homeowners, tenant...","[loan, purpos, 500, 75000, homeown, tenant, we...","[loan, purpose, 500, 75000, homeowner, tenant,..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...,congrats nokia 3650 video camera phone is your...,"[congrats, nokia, 3650, video, camera, phone, ...","[congrats, nokia, 3650, video, camera, phone, ...","[congrat, nokia, 3650, video, camera, phone, c...","[congrats, nokia, 3650, video, camera, phone, ..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar...","[urgent, mobile, number, awarded, 2000, prize,...","[urgent, mobil, number, award, 2000, prize, gu...","[urgent, mobile, number, award, 2000, prize, g..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contacted our dating service and e...,someone has contacted our dating service and e...,"[someone, has, contacted, our, dating, service...","[someone, contacted, dating, service, entered,...","[someon, contact, date, servic, enter, phone, ...","[someone, contact, date, service, enter, phone..."